### ISSUE TITLE
Plugins do not honor the `path` defined in the PROJECT file

### ISSUE THREAD

**Issue by AlmogBaku** [kubernetes-sigs/kubebuilder#2634] opened 2022-04-23 10:44 UTC
### What broke? What's expected?

When I configure a different path for my resource other than the default `./api` path, the plugins do not honor it, and expect the default path.

I found that it impacting the following:
1. go/v3: Creating a webhook for an existing API
3. Kustomize: Creating a new webhook

### Reproducing this issue

1. change https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/PROJECT#L27 this line to 

### KubeBuilder (CLI) Version

master

### PROJECT version

3

### Plugin versions

```yaml
- go.kubebuilder.io/v3
```

**Comment by camilamacedo86** [comment] 2022-04-25 21:56
You are looking here for the plugins to be able to work with different paths on the scaffolds and it is not supported. 
To provide a solution that allows users to customize the default layout path we would need to have a doc proposal for it and see how they can be defined and configure the paths for each scaffold dir. What we would do when the change/config is provided for a project that was scaffolded already and etc. 

So, this requirement is a duplication of: https://github.com/kubernetes-sigs/kubebuilder/issues/932.

**Comment by camilamacedo86** [comment] 2022-04-25 22:00
Could you please describe the steps to reproduce this issue? 
What do you mean with:
> When I configure a different path for my resource other than the default ./api path

We have only 2 possible paths the default layout and the multi-group layout. 
So, what are the circumstances where the path is not the default one in this case?

**Comment by camilamacedo86** [comment] 2022-04-26 12:01
Hi @AlmogBaku, 

Thank you for providing the info and the steps:

> clone https://github.com/kubernetes-sigs/kubebuilder/tree/master/testdata/project-v3/
> move the api package to a different location (i.e., pkg/api)
> update it accordingly in the PROJECT file
> try to generate a new webhook

This operation is **not** supported so we do not have a bug here. 
Kubebuilder does not support customizations of the paths and the info tracked in the PROJECT has not the purpose to allow this customization. 

Since you are looking here for the plugins to be able to work with different paths it shows a duplication of: https://github.com/kubernetes-sigs/kubebuilder/issues/932. After phase 2 users would be able to have their own plugins used with Kubebuilder that does the scaffolds in the paths that please them.

However, if you are looking for a way to make the available plugins be able to work with customizations of the paths then that cannot be addressed ONLY for the apis and should work in general with all that is a scaffold for the plugins. In this way, this RFE would be much more complex than the changes suggested here and we would need a design doc proposal to discuss the approach.

**Comment by camilamacedo86** [comment] 2022-07-01 09:50
Hi @AlmogBaku,

I hope that you do not mind. I am closing this one in favor of https://github.com/kubernetes-sigs/kubebuilder/issues/932. ( it is duplicated )

The above task is created to allow us to provide a feature where would be possible customize the path of what is scaffolded by default.

Note that the PROJECT file is used to track the info used to scaffold the projects and changing the behaviour reported as a bug is not supported. We could indeed try to add a comment on the top like:

```yaml
# Code generated by tool. DO NOT EDIT.
# This file is used to track the info used to scaffold your project
# and allow the plugins properly work.
```

But if we try to do so the current libs used to marchal / unmarchal the yaml will fail:

```
Error: unable to load the configuration: unable to determine config version: error converting YAML to JSON: yaml: line 18: mapping values are not allowed in this context
```

Because the comment is not ignored by them. However, I created a task to see if we can work on this, see: https://github.com/kubernetes-sigs/kubebuilder/issues/2786

PLease, feel free to reach out or re-open this one if you see fit.

**Closed by camilamacedo86** 2022-07-01 09:50 UTC
Labels: kind/bug
