### ISSUE TITLE
v2 option not working when initializing project for a custom controller over built-in resources 

### ISSUE THREAD

**Issue by LAnastasiia** [kubernetes-sigs/kubebuilder#1604] opened 2020-07-22 15:18 UTC
Hi,
I was trying to implement an admission controller over built-in resources by [this](https://book.kubebuilder.io/reference/webhook-for-core-types.html) example but could not initialize the project for that in version kubebuilder v2.

Here are the commands I ran and their outputs: 
`kubebuilder init --domain my.domain`
`kubebuilder create api --group "core" --kind "Pod" --version "v2"`
```
Create Resource [y/n]
n
Create Controller [y/n]
y
```
```
Writing scaffold for you to edit...
controllers/pod_controller.go
Running make:
$ make
/home/.../go/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
Error: go [list -e -json -compiled=true -test=false -export=false -deps=true -find=false -tags ignore_autogenerated -- ./...]: exit status 1: build check: cannot load k8s.io/api/core/v2: module k8s.io/api@latest found (v0.18.6), but does not contain package k8s.io/api/core/v2
...
```

from `k8s.io/api/core/v2: module k8s.io/api@latest found (v0.18.6), but does not contain package k8s.io/api/core/v2` message I figured it's only breaking for version 2 for some reason, and it does initialize the project successfully for "v1" option. 

Is it a bug or am I missing something here? Is support for controllers over built-in resources expected in version 2 of kubebuilder?

Kind regards

**Comment by camilamacedo86** [comment] 2020-08-15 18:32
Hi @LAnastasiia, 

It will face issues because the controllers will import try to import the type  but it does not exist since you : 

```
Create Resource [y/n]
n
```

Regards to allow work with core types where the group should be "empty instead". See: https://github.com/kubernetes-sigs/kubebuilder/issues/1404 . 


So, I am closing this as solved since it is the expected behaviour and to allow core types we have #1404 already. Also, please see the available workaround in the https://github.com/kubernetes-sigs/kubebuilder/issues/1404#issuecomment-662046117 to work with core types. 

However, also feel free to re-open if you see that something still need to be addressed here. 

/close
/assign @camilamacedo86

**Closed** 2020-08-15 18:32 UTC
