### ISSUE TITLE
In the latest version of kubebuilder. Something goes wrong with jobTemplate

### ISSUE THREAD

**Issue by Pluviophile225** [kubernetes-sigs/kubebuilder#3313] opened 2023-03-27 06:09 UTC
### What broke? What's expected?

When I follow the instruction of how to start and change the *cornjob_types.go*, then it goes wrong with `make install` like this.
```shell
[root@VM-4-8-centos kubebuilder]# make install
test -s /root/go/src/kubebuilder/bin/controller-gen && /root/go/src/kubebuilder/bin/controller-gen --version | grep -q v0.11.1 || \
GOBIN=/root/go/src/kubebuilder/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.11.1
/root/go/src/kubebuilder/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/root/go/src/kubebuilder/bin/kustomize build config/crd | kubectl apply -f -
The CustomResourceDefinition "cronjobs.batch.tutorial.kubebuilder.io" is invalid: 
* spec.validation.openAPIV3Schema.properties[spec].properties[jobTemplate].properties[spec].properties[template].properties[spec].properties[volumes].items.properties[ephemeral].properties[volumeClaimTemplate].properties[spec].properties[resources].properties[claims].items.x-kubernetes-map-type: Invalid value: "null": must be atomic as item of a list with x-kubernetes-list-type=set
* spec.validation.openAPIV3Schema.properties[spec].properties[jobTemplate].properties[spec].properties[template].properties[spec].properties[initContainers].items.properties[resources].properties[claims].items.x-kubernetes-map-type: Invalid value: "null": must be atomic as item of a list with x-kubernetes-list-type=set
* spec.validation.openAPIV3Schema.properties[spec].properties[jobTemplate].properties[spec].properties[template].properties[spec].properties[containers].items.properties[resources].properties[claims].items.x-kubernetes-map-type: Invalid value: "null": must be atomic as item of a list with x-kubernetes-list-type=set
* spec.validation.openAPIV3Schema.properties[spec].properties[jobTemplate].properties[spec].properties[template].properties[spec].properties[ephemeralContainers].items.properties[resources].properties[claims].items.x-kubernetes-map-type: Invalid value: "null": must be atomic as item of a list with x-kubernetes-list-type=set
make: *** [install] Error 1
```
However, if I change the version, it goes right.

### Reproducing this issue

Use the latest version to run the guidline book.

### KubeBuilder (CLI) Version

v3.9.1

**Comment by xiao-jay** [comment] 2023-03-27 06:11
see this https://github.com/kubernetes-sigs/kubebuilder/issues/3303#issuecomment-1475080334

**Comment by varshaprasad96** [comment] 2023-04-06 14:43
As @xiao-jay mentioned, this was a regression from upstream (ref: https://github.com/kubernetes-sigs/controller-tools/pull/754) happening because the field type was modified (https://github.com/kubernetes/kubernetes/pull/114617)

**Comment by camilamacedo86** [comment] 2023-04-22 08:41
Closing this one since it is a bug for controller-gen (tools), which is solved already as described in the above comment  https://github.com/kubernetes-sigs/kubebuilder/issues/3313#issuecomment-1499180545.  Kubebuilder default is scaffolded will be bumped to use the latest/next future release of controller tools when available. More info

**Closed by camilamacedo86** 2023-04-22 08:41 UTC
Labels: kind/bug
