### ISSUE TITLE
Hierarchy of kubebuilder controllers

### ISSUE THREAD

**Issue by champak** [kubernetes-sigs/kubebuilder#1053] opened 2019-09-30 14:06 UTC
Hi folks,
Has anyone attempted to build a hierarchy of kubebuilder generated controllers that control a CRD hierarchy. e.g CRD of kind "foo" is composed with instances of CRD kind "bar", and foo and bar both get reconciled possibly by separate controllers/operators. A different approach could be to have separate API groups but was wondering what may have worked better. Thanks

**Comment by champak** [comment] 2019-09-30 18:29
Found that invoking "kubebuilder create api ..." more than once after a single invocation of init with the same group seems to have worked. The generated main.go got updated with two instantiations of controllers via the SetupWitthManager() API, one for each kind. I have not yet found a mechanism to indicate dependancies between two kinds. Since it seems kubebuilder can anyways be used to reconcile resources that already have K8 native controllers am thinking layering one kubebuilder controller/kind over another controller/kind is not too far off.

**Comment by DirectXMan12** [comment] 2019-09-30 22:49
@champak are you saying you want something like

```go
ctrl.NewControllerManagedBy(mgr).
  For(&api.MyDeployment{}).
  Owns(&api.MyReplicaSet{}).
  Complete(&controllers.MyDeploymentsReconciler{})

ctrl.NewControllerManagedBy(mgr).
  For(&api.MyReplicaSet{}).
  Owns(&corev1.Pod{}).
  Complete(&controllers.MyReplicaSetsController{})
```

assuming `MyDeployment` and `MyReplicaSet` are two new CRDs that you created (with analogous relationships to those of the similarly-named built-in types)?

Custom resources act more-or-less the same as built-in resources, so generally approaches that work for built-in types should work for CRDs as well.

Closing for book-keeping purposes, feel free to keep commenting if this doesn't answer your question.

**Closed by DirectXMan12** 2019-09-30 22:49 UTC

**Comment by champak** [comment] 2019-10-01 13:59
@DirectXMan12  Thanks for your comment ! I was trying something pretty much on the lines that you described. I was instantiating both the controllers under the same group which seems legit, right ? here is what I tried

kubebuilder init --domain foobar.com
kubebuilder create api --group chat --version v1 --kind Foo
kubebuilder create api --group chat --version v1 --kind Bar

This scaffolded a main.go with two invocations of SetupWithManager:

	if err = (&controllers.FooReconciler{
		Client: mgr.GetClient(),
		Log:    ctrl.Log.WithName("controllers").WithName("Foo"),
	}).SetupWithManager(mgr); err != nil {
		setupLog.Error(err, "unable to create controller", "controller", "Foo")
		os.Exit(1)
	}
	if err = (&controllers.BarReconciler{
		Client: mgr.GetClient(),
		Log:    ctrl.Log.WithName("controllers").WithName("Bar"),
	}).SetupWithManager(mgr); err != nil {
		setupLog.Error(err, "unable to create controller", "controller", "Bar")
		os.Exit(1)
	}

I was getting Foo to own Bar which owns a Pod. So much like you described I had:

foo_controller.go:

func (r *FooReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&chatv1.Foo{}).
		Owns(&chatv1.Bar{}).
		Complete(r)
}

bar_controller.go:

func (r *BarReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&chatv1.Bar{}).
		Owns(&corev1.Pod{}).
		Complete(r)
}

I had updated the types file for bar to include a Pod:
type BarSpec struct {
	PodTempSpec corev1.PodTemplateSpec `json:"podTempSpec"`
}

and for Foo to include Bar

type FooSpec struct {
	Bar chatv1.Bar `json:"bar"` 
}

At this point the code generation failed. I got a stack with "make generate":

controller-gen object:headerFile=./hack/boilerplate.go.txt paths="./..."
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x985ddf]

goroutine 1 [running]:
go/types.(*Checker).handleBailout(0xc000934000, 0xc0000f3748)
	...go/src/go/types/check.go:240 +0x98
panic(0xb2c7c0, 0x118c7a0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:74
sigs.k8s.io/controller-tools/pkg/loader.(*loader).typeCheck.func1(0xc0008fe021, 0xf, 0x0, 0x0, 0x0)
	.../pkg/mod/sigs.k8s.io/controller-tools@v0.2.1/pkg/loader/loader.go:255 +0xaf
sigs.k8s.io/controller-tools/pkg/loader.importerFunc.Import(0xc0007a44b0, 0xc0008fe021, 0xf, 0x0, 0x0, 0xbfa900)
	..../mod/sigs.k8s.io/controller-tools@v0.2.1/pkg/loader/loader.go:361 +0x3a
go/types.(*Checker).importPackage(0xc000934000, 0xe0f, 0xc0008fe021, 0xf, 0xc0002518c0, 0x25, 0x0)
	/usr/local/go/src/go/types/resolver.go:161 +0x612
go/types.(*Checker).collectObjects(0xc000934000)
	/usr/local/go/src/go/types/resolver.go:256 +0x15d9
go/types.(*Checker).checkFiles(0xc000934000, 0xc0002eb080, 0x3, 0x3, 0x0, 0x0)
.............

I think perhaps I am missing annotations that need to be manually added for this case. I am looking at the controller-gen documentation for annotations but have not located anything related to this yet. Since the panic is on a mutex wondering if controller-gen got spooked by one CRD spec referring to another...

**Comment by champak** [comment] 2019-10-01 14:09
The controller-gen version was:
go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.1
kubebuilder:
Version: version.Version{KubeBuilderVersion:"2.0.1", KubernetesVendor:"1.14.1"

**Comment by DirectXMan12** [comment] 2019-10-04 22:50
The panic is a bug, but I *think* this issue is that Foo and Bar are in the same package, so you don't need the package specifier -- you can do

```go
type FooSpec struct {
    Bar Bar `json:"bar"`
```

Separately, usually you wouldn't embed the full object, you'd just embed the spec + some metadata (like podtemplatespec).

**Comment by DirectXMan12** [comment] 2019-10-04 22:51
(panic is a bug in that panics like that shouldn't exist)

**Comment by champak** [comment] 2019-10-07 14:26
@DirectXMan12 removing the package specifier did not fix the panic. What I am interested in achieving is to compose multiple layers of the custom controllers. In this instance it would be the Foo controller managing Foo objects at a higher level than the Bar controller which would manage the Bar object much on the lines of the Deployment->Replicaset relationship. Like you mentioned since Deployments and Replicasets are implemented with controllers I was expecting similar things could be made to work for custom resources and multiple levels of reconciliation can be built. Therein I am assuming there exists some infrastructure that enables propagation of Reconciliation requests from one layer to the next.

I could embed the spec from Bar into Foo but would that not mean we will have a single controller i.e for Foo ? Maybe I misunderstood your suggestion

**Comment by DirectXMan12** [comment] 2019-10-07 21:26
First off: with the latest copy of KubeBuilder plus controller-tools v0.2.1, I cannot reproduce the panic that you mentioned.  Please ensure that you're using an up-to-date copy of controller-tools -- run `go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.1` if you're running off of a copy installed via `go get`.

Secondly, it's unclear why you want to embed the *entire* `Bar`, status, typemeta, and all.  If you look at the relationship between ReplicaSet and Deployment, you can see that Deployment itself just has a subset of replicaset -- in the case of deployment, it includes the PodTemplateSpec, plus replicas and selector.  Similarly, if we look at the relationship between ReplicaSet and Pod, we see that we're using PodTemplateSpec in the ReplicaSet spec, not Pod.  PodTemplateSpec includes metadata + spec, w/o status or typemeta.

Generally the pattern is "if Foo creates/manages Bar, then the FooSpec should contain some subset of the BarSpec".  Does that make sense?

**Comment by champak** [comment] 2019-10-08 20:36
@DirectXMan12 Thanks for describing the pattern. I had been thinking there would be more code reuse if we were to embed all of one struct into another but that is not the approach that Replicaset/Deployment have taken; much of the code anyways is well encapsulated into kubebuilder/controller-runtime so isnt much redundancy anyways to have both controllers around. Like you described a subset of the constituents of the BarSpec can be in FooSpec and that works.  

Regarding the crash I was using controller-tools v0.2.1 and my kubebuilder was also quite new (KubeBuilderVersion:"2.0.1", BuildDate:"2019-09-24T17:37:32Z"). Perhaps some other dependancy is off but the approach anyways seems like an anti-pattern.
