### ISSUE TITLE
Kustomize not found

### ISSUE THREAD

**Issue by jehutyy** [kubernetes-sigs/kubebuilder#1921] opened 2020-12-21 13:11 UTC
Following documentation [here](https://book.kubebuilder.io/quick-start.html)

It is stated:
```
Projects created by Kubebuilder contain a Makefile 
that will install tools at versions defined at creation time. Those tools are:

    kustomize
    controller-gen

The versions which are defined in the Makefile and go.mod files are the 
versions tested and therefore is recommend to use the specified versions.
```
Though when running `make install` I get the following error : 
```
go: found sigs.k8s.io/controller-tools/cmd/controller-gen in sigs.k8s.io/controller-tools v0.2.5
/root/go/bin/controller-gen "crd:trivialVersions=true" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
kustomize build config/crd | kubectl apply -f -
/bin/sh: 1: kustomize: not found
error: no objects passed to apply
make: *** [Makefile:30: install] Error 1

```

**Comment by camilamacedo86** [comment] 2020-12-21 14:17
What is the tool version used? Are you using 3.0.0-alpha or 2.3.1 to create the project? Also, what is SO used by you in your local env? Could you please add here the content of your kustomize target?

**Comment by jehutyy** [comment] 2020-12-22 15:00
kubebuilder version:

```
buster:~# kubebuilder version
Version: version.Version{KubeBuilderVersion:"2.3.1", KubernetesVendor:"1.16.4", GitCommit:"8b53abeb4280186e494b726edf8f54ca7aa64a49", BuildDate:"2020-03-26T16:42:00Z", GoOs:"unknown", GoArch:"unknown"}
```

Here Install target:
```
 29 install: manifests
 30         kustomize build config/crd | kubectl apply -f -
```

**Comment by camilamacedo86** [comment] 2020-12-24 10:30
Hi @jehutyy,

Shows that the problem is that your local env is unable to process the shell commands in the Makefile. The solution https://github.com/kubernetes-sigs/kubebuilder/pull/1725/files#diff-eaeaa01fcbb2369db04d65fec624e00dd2e31c0ad08fb7abbbd146d1ae1db1f4R60-R62 point out the bin/bash might solve your problem. Could you please check and let us know?

**Comment by jehutyy** [comment] 2020-12-24 12:25
Hi,

I set `SHELL = /bin/bash` at the top of Makefile file without success.

If I understand well, there should be a target in Makefile which will install kustomize and controller-gen right ? 
If so it seems that it is not the case and thus `install` target will fail because of that.

**Comment by jehutyy** [comment] 2020-12-24 12:44
I got it working by downloading kustomize binary by myself. 

I don't know if it should work that way, or `Makefile` should download it itself.

**Comment by camilamacedo86** [comment] 2021-01-12 16:16
Hi @jehutyy, 

The problem is that you are using an old version of the project. for the latest versions, you will check that your makefile will be scaffolded with; (which can manually be added to your project to solve the problem)

```
# Download kustomize locally if necessary
KUSTOMIZE = $(shell pwd)/bin/kustomize
kustomize:
	$(call go-get-tool,$(KUSTOMIZE),sigs.k8s.io/kustomize/kustomize/v3@v3.8.7)
```

Then, the above code will install the kustomize and because of this, it is no longer a requirement. I'd like to suggest you upgrade your project to the latest ones and use the latest version of the tool 3.0.0-alpha-1. You can check [here](https://book.kubebuilder.io/migration/guide.html) the migration guide from v1 to v2 and we have a PR with the steps from v2 to v3 see [here](https://github.com/kubernetes-sigs/kubebuilder/pull/1916).

The migration journey basically is you re-create the project(kubebuilder init) and scaffold the APIS(kubebuilder create api) with the latest version of the tool and push your apis/controllers/main.go content to the new files scaffolds. 

I am closing this one as sorted out. however, please feel free to ping us your raise new issues if you need.

**Closed by camilamacedo86** 2021-01-12 16:16 UTC

**Comment by skuethe** [comment] 2021-02-15 15:22
I'd like to pick up on this issue - I have the exact same behaviour, and I just started today with a totally fresh install of `go`, `kubebuilder` and a new project created by `kubebuilder init --domain my.domain`. So I would feel this could not be a problem of some "old project version".

I also used the quick start documentation:
https://book.kubebuilder.io/quick-start.html

For comparison I downloaded four different versions of kubebuilder and looked at how they behave (or rather If they have the correct `Makefile` we need):

**kubebuilder v2.3.0**:
```bash
~/go/src/example230$ /tmp/kubebuilder_2.3.0_linux_amd64/bin/kubebuilder version
Version: version.Version{KubeBuilderVersion:"2.3.0", KubernetesVendor:"1.16.4", GitCommit:"800f63a7e41a6a8016d4cb9d583e1705b0812c9d", BuildDate:"2020-02-28T19:15:41Z", GoOs:"unknown", GoArch:"unknown"}

~/go/src/example230$ /tmp/kubebuilder_2.3.0_linux_amd64/bin/kubebuilder init --domain my.domain
[...]

~/go/src/example230$ grep -ri "kustomize" Makefile
kustomize build config/crd | kubectl apply -f -
kustomize build config/crd | kubectl delete -f -
cd config/manager && kustomize edit set image controller=${IMG}
kustomize build config/default | kubectl apply -f -

~/go/src/example230$ grep -i "version" PROJECT
version: "2"
```

**kubebuilder v2.3.1**:
```bash
~/go/src/example231$ /tmp/kubebuilder_2.3.1_linux_amd64/bin/kubebuilder version
Version: version.Version{KubeBuilderVersion:"2.3.1", KubernetesVendor:"1.16.4", GitCommit:"8b53abeb4280186e494b726edf8f54ca7aa64a49", BuildDate:"2020-03-26T16:42:00Z", GoOs:"unknown", GoArch:"unknown"}

~/go/src/example231$ /tmp/kubebuilder_2.3.1_linux_amd64/bin/kubebuilder init --domain my.domain
[...]

~/go/src/example231$ grep -ri "kustomize" Makefile
kustomize build config/crd | kubectl apply -f -
kustomize build config/crd | kubectl delete -f -
cd config/manager && kustomize edit set image controller=${IMG}
kustomize build config/default | kubectl apply -f -

~/go/src/example231$ grep -i "version" PROJECT
version: "2"
```

**kubebuilder v3.0.0-alpha.1**:
```bash
~/go/src/example300alpha1$ /tmp/kubebuilder_linux_amd64 version
Version: main.version{KubeBuilderVersion:"3.0.0-alpha.1", KubernetesVendor:"1.19.2", GitCommit:"1428bba7c162cf2b783c89fd6f07f4efbae97130", BuildDate:"2021-01-08T22:30:36Z", GoOs:"linux", GoArch:"amd64"}

~/go/src/example300alpha1$ /tmp/kubebuilder_linux_amd64 init --domain my.domain
[...]

~/go/src/example300alpha1$ grep -ri "kustomize" Makefile
install: manifests kustomize
        $(KUSTOMIZE) build config/crd | kubectl apply -f -
uninstall: manifests kustomize
        $(KUSTOMIZE) build config/crd | kubectl delete -f -
deploy: manifests kustomize
        cd config/manager && $(KUSTOMIZE) edit set image controller=${IMG}
        $(KUSTOMIZE) build config/default | kubectl apply -f -
        $(KUSTOMIZE) build config/default | kubectl delete -f -
# Download kustomize locally if necessary
KUSTOMIZE = $(shell pwd)/bin/kustomize
kustomize:
        $(call go-get-tool,$(KUSTOMIZE),sigs.k8s.io/kustomize/kustomize/v3@v3.8.7)

~/go/src/example300alpha1$ grep -i "version" PROJECT
version: 3-alpha
```

**kubebuilder latest**:
```bash
~/go/src/examplelatest$ /tmp/kubebuilder version
Version: main.version{KubeBuilderVersion:"v0.0.0-SNAPSHOT-c82530b", KubernetesVendor:"1.19.2", GitCommit:"c82530b1d30e9713adbd34241dd2549b317ea421", BuildDate:"2021-02-11T20:39:56Z", GoOs:"linux", GoArch:"amd64"}

~/go/src/examplelatest$ /tmp/kubebuilder init --domain my.domain
[...]

~/go/src/examplelatest$ grep -ri "kustomize" Makefile
install: manifests kustomize ## Install CRDs into the K8s cluster specified in ~/.kube/config.
        $(KUSTOMIZE) build config/crd | kubectl apply -f -
uninstall: manifests kustomize ## Uninstall CRDs from the K8s cluster specified in ~/.kube/config.
        $(KUSTOMIZE) build config/crd | kubectl delete -f -
deploy: manifests kustomize ## Deploy controller to the K8s cluster specified in ~/.kube/config.
        cd config/manager && $(KUSTOMIZE) edit set image controller=${IMG}
        $(KUSTOMIZE) build config/default | kubectl apply -f -
        $(KUSTOMIZE) build config/default | kubectl delete -f -
KUSTOMIZE = $(shell pwd)/bin/kustomize
kustomize: ## Download kustomize locally if necessary.
        $(call go-get-tool,$(KUSTOMIZE),sigs.k8s.io/kustomize/kustomize/v3@v3.8.7)

~/go/src/examplelatest$ grep -i "version" PROJECT
version: "3"
```


So what can we get from this?
Starting with `v3.0.0-alpha.1` (maybe already alpha.0), the KUSTOMIZE install option is available in the Makefile.

Other (maybe related findings):
The `GoOs` and `GoArch` variables of the `kubebuilder version` output are set to `unknown` in releases `v2.3.0` and `v2.3.1`.
With the `v3.0.0-alpha.1` release, the variables are set correctly.

So maybe this is a problem with the v2.3.1 / v2.3.0 versions of linux amd64? Or rather they do something completely different than the version 3?

It is to mention that I use Ubuntu on WSL2.0:
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```
