### ISSUE TITLE
Install docs not clear

### ISSUE THREAD

**Issue by sebgoa** [kubernetes-sigs/kubebuilder#647] opened 2019-03-25 09:12 UTC
Hi,

I tried to use `kubebuilder` for the first time. Followed the kubebuilder book.

First, after getting it installed I tried to init into a regular directory and:

```
$ kubebuilder init --domain k8s.io --license apache2 --owner "The Kubernetes Authors"
2019/03/25 09:57:01 kubebuilder must be run from the project root under $GOPATH/src/<package>. 
Current GOPATH=/Users/sebastiengoasguen/Documents/go.  
Current directory=/Users/sebastiengoasguen/Documents/gitforks/oreilly-kubernetes/kbuilder
```

So it looks like I need to be in my $GOPATH

Then after creating a new dir inside my $GOPATH:

```
$ kubebuilder init --domain k8s.io --license apache2 --owner "The Kubernetes Authors"
Run `dep ensure` to fetch dependencies (Recommended) [y/n]?
y
dep ensure
Running make...
make
go generate ./pkg/... ./cmd/...
go fmt ./pkg/... ./cmd/...
go vet ./pkg/... ./cmd/...
# github.com/triggermesh/kbuilder/cmd/manager [github.com/triggermesh/kbuilder/cmd/manager.test]
cmd/manager/main.go:50:47: unknown field 'MetricsBindAddress' in struct literal of type manager.Options
make: *** [vet] Error 2
2019/03/25 10:07:36 exit status 2
```

The `dep ensure` took a long time and I thought there was an issue. But then I saw progress and the error.

This is the latest 1.0.8 release on OSX, with copy paste from the kubebuilder book

**Comment by davidewatson** [comment] 2019-04-04 22:44
I just had the same thing happen to me. It turned out to be a `dep` bug. Removing the `dep` cache fixed it (e.g. `rm -rf "${GOPATH}/pkg/dep/"`). If you agree I think this issue can be closed now...

```
rodin:cluster-api-machine-webhook-maas dwat$ kubebuilder init --domain infra.cluster.k8s.io --license apache2 --owner "The Kubernetes Authors"
Run `dep ensure` to fetch dependencies (Recommended) [y/n]?
y
dep ensure
Running make...
make
go generate ./pkg/... ./cmd/...
go fmt ./pkg/... ./cmd/...
go vet ./pkg/... ./cmd/...
# github.com/cattlek8s/cluster-api-machine-webhook-maas/cmd/manager [github.com/cattlek8s/cluster-api-machine-webhook-maas/cmd/manager.test]
cmd/manager/main.go:50:47: unknown field 'MetricsBindAddress' in struct literal of type manager.Options
make: *** [vet] Error 2
2019/04/04 15:31:11 exit status 2
rodin:cluster-api-machine-webhook-maas dwat$
```
```
rodin:cluster-api-machine-webhook-maas dwat$ rm -rf "${GOPATH}/pkg/dep/"
```
```
rodin:cluster-api-machine-webhook-maas dwat$ kubebuilder init --domain infra.cluster.k8s.io --license apache2 --owner "The Kubernetes Authors"
Run `dep ensure` to fetch dependencies (Recommended) [y/n]?
y
dep ensure
Running make...
make
go generate ./pkg/... ./cmd/...
go fmt ./pkg/... ./cmd/...
go vet ./pkg/... ./cmd/...
go run vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go all
CRD manifests generated under '/Users/dwat/workspace/go/src/github.com/cattlek8s/cluster-api-machine-webhook-maas/config/crds' 
RBAC manifests generated under '/Users/dwat/workspace/go/src/github.com/cattlek8s/cluster-api-machine-webhook-maas/config/rbac' 
go test ./pkg/... ./cmd/... -coverprofile cover.out
?   	github.com/cattlek8s/cluster-api-machine-webhook-maas/pkg/apis	[no test files]
?   	github.com/cattlek8s/cluster-api-machine-webhook-maas/pkg/controller	[no test files]
?   	github.com/cattlek8s/cluster-api-machine-webhook-maas/pkg/webhook	[no test files]
?   	github.com/cattlek8s/cluster-api-machine-webhook-maas/cmd/manager	[no test files]
go build -o bin/manager github.com/cattlek8s/cluster-api-machine-webhook-maas/cmd/manager
Next: Define a resource with:
$ kubebuilder create api
rodin:cluster-api-machine-webhook-maas dwat$ 
```

**Comment by DirectXMan12** [comment] 2019-04-08 21:54
closing as per the above comments

**Comment by wjcaitu** [comment] 2019-04-23 08:45
using  rm -rf "${GOPATH}/pkg/dep/"  does not work, i think the dep of controller-runtime is initialized incorrectly by kubebuilder

**Comment by wjcaitu** [comment] 2019-04-23 08:56
when i change the version of controller-runtime to "v0.1.10", it works. So the problem is the Gopkg.toml which generated by kubebuilder contains invalid constraint of controller-runtime

**Comment by shadiramadan** [comment] 2019-05-14 05:10
I'm running into the same set of issues.

**Closed** 2019-05-30 01:12 UTC
