### ISSUE TITLE
Validation for core.Volume with a SecretVolumeSource requires specifying "type: array"

### ISSUE THREAD

**Issue by trisberg** [kubernetes-sigs/kubebuilder#1128] opened 2019-10-25 16:05 UTC
I've created a CRD that has a spec field defines as:

```
	// Template volume
	Template *corev1.Volume `json:"template,omitempty"`
```

This generates validation for the CRD and when I try to create an instance of the CRD I get validation error if I don't provide a `type: array` as part of the SecretVolumeSource for the Volume definition.

```
apiVersion: test.example.com/v1alpha1
kind: Example
metadata:
  name: mytest
spec:
  template:
    name: myvolume
    secret:
      type: array
      secretName: test-secret
      items:
      - key: pasword
        path: password
```

If I leave out `type: array` I get this validation error:

```
$ k apply -f -
apiVersion: test.example.com/v1alpha1
kind: Example
metadata:
  name: mytest
spec:
  template:
    name: myvolume
    secret:
      secretName: test-secret
      items:
      - key: pasword
        path: password
The Example "mytest" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"test.example.com/v1alpha1", "kind":"Example", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"test.example.com/v1alpha1\",\"kind\":\"Example\",\"metadata\":{\"annotations\":{},\"name\":\"mytest\",\"namespace\":\"default\"},\"spec\":{\"template\":{\"name\":\"myvolume\",\"secret\":{\"items\":[{\"key\":\"pasword\",\"path\":\"password\"}],\"secretName\":\"test-secret\"}}}}\n"}, "creationTimestamp":"2019-10-25T15:59:27Z", "generation":1, "name":"mytest", "namespace":"default", "uid":"6c054e4d-f740-11e9-9d56-42010a8000cc"}, "spec":map[string]interface {}{"template":map[string]interface {}{"name":"myvolume", "secret":map[string]interface {}{"items":[]interface {}{map[string]interface {}{"key":"pasword", "path":"password"}}, "secretName":"test-secret"}}}}: validation failure list:
type in spec.template.secret is required
```

I've never had to provide this `type: array` definition when using a SecretVolumeSource for a Deployment or Pod before.

Any thoughts on this? My code is in https://github.com/trisberg/test

**Comment by DirectXMan12** [comment] 2019-11-06 01:39
o_O  what kubernetes version are you testing against?

**Comment by trisberg** [comment] 2019-11-06 13:26
I'm currently using v1.14.7

**Comment by trisberg** [comment] 2019-11-06 16:05
I also tried it on a new kind cluster running "v1.15.3", same error

**Comment by DirectXMan12** [comment] 2019-11-06 22:01
hmm... does not reproduce on master kubernetes, but I can reproduce on 1.15.5 (from go.kubebuilder.io/test-tools), digging in

**Comment by trisberg** [comment] 2019-11-06 22:27
initially used kubebuilder 2.0.1, just tested with the latest 2.1.0, same problem

**Comment by camilamacedo86** [comment] 2019-11-14 14:13
HI @trisberg, 

Just to ensure, if you have time could you check with the master branch as well? May it can be solved.

**Comment by trisberg** [comment] 2019-11-18 19:57
Tested with current master branch and get the same results

**Comment by trisberg** [comment] 2019-11-18 19:59
That's with the current master branch of kubebuilder. Did you mean that  or did you mean latest master of kubernetes?

**Comment by trisberg** [comment] 2019-11-18 20:14
I tested against a `v1.17.0-beta.2` cluster and that seems to work, I did not get this error.

**Comment by camilamacedo86** [comment] 2019-11-18 20:17
Hi @trisberg, 

The API rules validations in Kube have been changing you probably upgrade the k8s version and then started to face it. For further information see the [API rules](https://github.com/kubernetes/kubernetes/tree/36981002246682ed7dc4de54ccc2a96c1a0cbbdb/api/api-rules ) documentation.

**Comment by trisberg** [comment] 2019-11-18 20:54
Yes, seems the validation is changing. Seems a bit strange though that the generated validation only works for 1.17 and not for older version that are the ones that can be found as hosted offerings like GKE.

**Comment by DirectXMan12** [comment] 2019-12-05 23:54
Yeah, this is a bug straight up I think, I don't think it's just due to the rules changing (unless someone has more details).  @sttts do you have any idea what's going on here?

**Comment by sttts** [comment] 2019-12-06 15:07
This was a bug in go-openapi. We fixed it in https://github.com/kubernetes/kubernetes/pull/85223. It happens in connection with `items` fields, very ugly. I wonder whether we can backport https://github.com/kubernetes/kubernetes/pull/85223. cc @liggitt wdyt?

**Comment by sttts** [comment] 2019-12-06 15:08
I think the very case here from the issue was already fixed in https://github.com/kubernetes/kubernetes/pull/76124, which is part of 1.16.

**Comment by liggitt** [comment] 2019-12-06 15:13
both kubernetes/kubernetes#85223 and kubernetes/kubernetes#76124 are larger than I would prefer to backport, especially for something that is not a regression (if I'm reading this correctly, this was broken in older releases and works in 1.16+?)

**Comment by sttts** [comment] 2019-12-06 15:21
A regression long ago.

**Closed** 2020-05-04 16:55 UTC
Labels: lifecycle/rotten
