### ISSUE TITLE
:book: migrating guide contains incomplete information

### ISSUE THREAD

**Issue by Sajiyah-Salat** [kubernetes-sigs/kubebuilder#3382] opened 2023-05-02 03:50 UTC
### What broke? What's expected?

https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/migrations.md
migration guide contains just two lines. 

There should be detail information about how to migrate. 

### Reproducing this issue

https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/migrations.md 
visit this link. 

### KubeBuilder (CLI) Version

3.10

**Comment by Sajiyah-Salat** [comment] 2023-05-02 03:51
/assign
I would like to work on this. right after the issue got accepted. 
cc: @camilamacedo86

**Comment by camilamacedo86** [comment] 2023-05-02 08:37
It is the header of a section. You must need to navegate on it, Please, see: https://book.kubebuilder.io/migrations.html

See the menu in the left:

<img width="1291" alt="Screenshot 2023-05-02 at 09 35 46" src="https://user-images.githubusercontent.com/7708031/235619027-bc6be563-9958-45ae-a374-2303c45af556.png">

Closing this one as deffered. 
Have only those lines in this doc is not a bug and it is the expected current behaviour.

**Closed by camilamacedo86** 2023-05-02 08:37 UTC
Labels: kind/bug
