### ISSUE TITLE
multiple api in one project raise error

### ISSUE THREAD

**Issue by wnz27** [kubernetes-sigs/kubebuilder#3667] opened 2023-10-23 01:13 UTC
### What broke? What's expected?

when create the two group api raise error:
Error: failed to create API: unable to inject the resource to "base.go.kubebuilder.io/v4": API resource already exists

i followe this doc: https://kubebuilder.io/migration/multi-group.html

and i project file is :
```shell
# Code generated by tool. DO NOT EDIT.
# This file is used to track the info used to scaffold your project
# and allow the plugins properly work.
# More info: https://book.kubebuilder.io/reference/project-config.html
domain: tutorial.kubebuilder.io
layout:
- go.kubebuilder.io/v4
multigroup: true
projectName: operator-demo
repo: tutorial.kubebuilder.io/operator-demo
resources:
- api:
    crdVersion: v1
    namespaced: true
  controller: true
  domain: tutorial.kubebuilder.io
  group: batch
  kind: CronJob
  path: tutorial.kubebuilder.io/operator-demo/api/v1
  version: v1
- api:
    crdVersion: v1
    namespaced: true
  controller: true
  domain: tutorial.kubebuilder.io
  group: back-end
  kind: BizServer
  path: tutorial.kubebuilder.io/operator-demo/api/back-end/v1
  version: v1
version: "3"

```
and i project tree is :

<img width="243" alt="截屏2023-10-23 09 12 23" src="https://github.com/kubernetes-sigs/kubebuilder/assets/12094918/76e83f2c-dfee-450f-8961-6390cb451668">

### Reproducing this issue

```shell
 kubebuilder create api --group back-end --version v1 --kind BizServer
INFO[0000] Create Resource [y/n]                        
y
INFO[0001] Create Controller [y/n]                      
y
Error: failed to create API: unable to inject the resource to "base.go.kubebuilder.io/v4": API resource already exists
Usage:
  kubebuilder create api [flags]

Examples:
  # Create a frigates API with Group: ship, Version: v1beta1 and Kind: Frigate
  kubebuilder create api --group ship --version v1beta1 --kind Frigate

  # Edit the API Scheme

  nano api/v1beta1/frigate_types.go

  # Edit the Controller
  nano internal/controller/frigate/frigate_controller.go

  # Edit the Controller Test
  nano internal/controller/frigate/frigate_controller_test.go

  # Generate the manifests
  make manifests

  # Install CRDs into the Kubernetes cluster using kubectl apply
  make install

  # Regenerate code and run against the Kubernetes cluster configured by ~/.kube/config
  make run


Flags:
      --controller           if set, generate the controller without prompting the user (default true)
      --force                attempt to create resource even if it already exists
      --group string         resource Group
  -h, --help                 help for api
      --kind string          resource Kind
      --make make generate   if true, run make generate after generating files (default true)
      --namespaced           resource is namespaced (default true)
      --plural string        resource irregular plural form
      --resource             if set, generate the resource without prompting the user (default true)
      --version string       resource Version

Global Flags:
      --plugins strings   plugin keys to be used for this subcommand execution

FATA[0002] failed to create API: unable to inject the resource to "base.go.kubebuilder.io/v4": API resource already exists 
```

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.12.0", KubernetesVendor:"1.27.1", GitCommit:"b48f95cd5384eadcdfd02a47a02910f72ddc7ea8", BuildDate:"2023-09-06T06:04:11Z", GoOs:"darwin", GoArch:"arm64"}

### PROJECT version

3

### Plugin versions

```yaml
layout:
- go.kubebuilder.io/v4
```

### Other versions

go version : 1.20
kubectl version: 
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.5-tke.19", GitCommit:"f38c2957c3b7e62c9777d6d8b5ccfc69aff20688", GitTreeState:"clean", BuildDate:"2023-08-01T10:02:03Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"}

**Comment by wnz27** [comment] 2023-10-23 01:47
if have a api , the first exec the create  the second creat api command raise this error:
```shell
FATA[0035] failed to create API: unable to run post-scaffold tasks of "base.go.kubebuilder.io/v4": exit status 1 
```

**Comment by camilamacedo86** [comment] 2023-11-02 04:36
Hi @wnz27,

See the error:

> failed to create API: unable to inject the resource to "base.go.kubebuilder.io/v4": API resource already exists

The problem is that you are trying to create another API with the same Group Kind Version. 

Note that we test it for all PR changes.
You can check here in the samples under the testdata that multiple APIs are generated for those:

https://github.com/kubernetes-sigs/kubebuilder/tree/master/testdata

I am closing this one as sorted out. 
But if you still need help, please feel free to re-open.

**Closed by camilamacedo86** 2023-11-02 04:36 UTC
Labels: kind/bug

**Comment by wnz27** [comment] 2023-11-29 12:46
> Hi @wnz27,
> 
> See the error:
> 
> > failed to create API: unable to inject the resource to "base.go.kubebuilder.io/v4": API resource already exists
> 
> The problem is that you are trying to create another API with the same Group Kind Version.
> 
> Note that we test it for all PR changes. You can check here in the samples under the testdata that multiple APIs are generated for those:
> 
> https://github.com/kubernetes-sigs/kubebuilder/tree/master/testdata
> 
> I am closing this one as sorted out. But if you still need help, please feel free to re-open.

ok， thank u explain， i try to view u links
