### ISSUE TITLE
controller-gen v0.4.0 do not generate config/webhook/manifests.yaml

### ISSUE THREAD

**Issue by wsq704252212** [kubernetes-sigs/kubebuilder#1924] opened 2020-12-30 07:18 UTC
After i  make manifests, controller-gen 0.2.5 will generate config/webhook/manifests.yaml, while  controller-gen 0.4.0 doesn't work. I have tried to add webhookVersions: v1beta1,  sideEffects: NoneOnDryRun to the comment // +kubebuilder:webhook: , it still doesn't work.

**Comment by camilamacedo86** [comment] 2020-12-30 09:18
Hi @wsq704252212,

If you use the alpha release then, kubebuilder will use the version 0.4.1 of controller gen where I could check that the manifest file is generated succefully. See: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/config/webhook/manifests.yaml

Also, if you use the v2/ plugin version it will use the version 0.3.0 where the file is also generated successfully. See: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v2/config/webhook/manifests.yaml

So, could you please provide the following information for we are able to try to help you with? Also, could you please provide a clear and concise description of the steps you took and indeed insert a code snippet when is required? Note that we need to be able to reproduce your problem, otherwise, it is very hard to help you with it,  

1. Are you creating a new project or are you using an old one created by the tool? Did you try to upgrade this project for an upper version? 
2. What is the kb version used locally?
3. Could you please provide the content of the files PROJECT file, go.mod and Makefile? 
4. What did you do?
5. What did you expect to see?
6. What did you see instead? Under which circumstances?

We are looking for your answers.

**Comment by wsq704252212** [comment] 2020-12-30 11:42
Thank you for your reply！

I use kubebuilder 2.3.1.

I do the following:

```
kubebuilder init --domain my.domain
kubebuilder create api --group batch --version v1 --kind CronJob
kubebuilder create webhook --group batch --version v1 --kind CronJob --defaulting --programmatic-validation
```

then I modify Makefile from
```
go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.5 ;\
```
to 
```
go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.0 ;\
```

After I make manifests, it does not generate config/webhook/manifests.yaml.

Maybe I should not use kubebuilder 2.3.1 with controller-gen 0.4.0?

**Comment by camilamacedo86** [comment] 2021-01-12 16:20
It will not work since the upper version of the controller-gen has breaking changes and requires other changes. 
Note that the official suported/tested versions are that ones which are scaffolded for the projects initialized for each tool/kb client version and plugin used. 

In this way, I'd recommend you download the latest release 3.0.0-alpha-1 and use it instead. The projects will be scaffolded with the latest/upper controller-gen version and will work well as expected. 

I am closing this as sorted out. However,  please feel free to raise new issues if you need any help with.

**Closed by camilamacedo86** 2021-01-12 16:20 UTC
