### ISSUE TITLE
Verifications for resource.Quantity

### ISSUE THREAD

**Issue by sophieliu15** [kubernetes-sigs/kubebuilder#1486] opened 2020-04-29 21:05 UTC
I have a field of type `resource.Quantity` in my CRD. I am trying to validate the value in case resource.Quantity#UnmarshalJSON fails on a persisted value. However, I did not find any related [verification markers](https://book.kubebuilder.io/reference/markers/crd-validation.html) for `resource.Quantity`. 

Do we need to verify the value is valid? Is there a best practice for how we should verify the value, e.g., using a combination of multiple verification primitives?  

/triage support

**Comment by CharlyF** [comment] 2020-08-27 22:39
👋  I am in a similar situation where I was using a `tolerance` parameter as a float but that is not working anymore: https://github.com/kubernetes-sigs/controller-tools/issues/245

I am ok with using a resource.Quantity, but I would like to be able to specify something like:
```
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:ExclusiveMinimum=true
	// +kubebuilder:validation:Maximum=1
	// +kubebuilder:validation:ExclusiveMaximum=true
```
 for the `resource.Quantity`.

/remove-lifecycle stale

**Comment by camilamacedo86** [comment] 2020-10-26 12:12
Hi @CharlyF and  @sophieliu15, 

What is the controller-tools version used by you? The projects have been scaffolded with `v0.3.0`. Could you please let us know if you still facing issues with this version? If yes, could you please describe the steps detailed with an snippet code for we are able to reproduce?

**Comment by camilamacedo86** [comment] 2020-11-03 12:44
We need here check if this scenario is not already solved with the version which is scaffolded currently and/or in the controller-tools. Also, see that we have an issue already that will be solved with the upgrade of controller-tools: https://github.com/kubernetes-sigs/kubebuilder/issues/1634

**Comment by camilamacedo86** [comment] 2020-11-05 21:32
Hi @CharlyF and @sophieliu15, 

Regards your scenario:  https://github.com/kubernetes-sigs/kubebuilder/issues/1486#issuecomment-682226229

I checked it with master branch and the plugin go/v2 which uses the controller-gen 0.3.0 and also with the go/v3-alpha that uses now 0.4.0 and in both scenarios it worked:

**Type definition**
```go
// AdmiralSpec defines the desired state of Admiral
type AdmiralSpec struct {
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	// Foo is an example field of Admiral. Edit Admiral_types.go to remove/update
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:validation:ExclusiveMinimum=true
	// +kubebuilder:validation:Maximum=1
	// +kubebuilder:validation:ExclusiveMaximum=true
	Foo int `json:"foo,omitempty"`
}
```

Then, CRD: 

```yaml
spec:
          description: AdmiralSpec defines the desired state of Admiral
          properties:
            foo:
              description: Foo is an example field of Admiral. Edit Admiral_types.go
                to remove/update
              exclusiveMaximum: true
              exclusiveMinimum: true
              maximum: 1
              minimum: 0
              type: integer
          type: object
```

Regards https://github.com/kubernetes-sigs/kubebuilder/issues/1486#issue-609359386,  you can use the [markers](https://book.kubebuilder.io/reference/markers/crd-validation.html) to generate validations are please you. The [k8s crd doc validation](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation) section might help you with. 

However, if you are trying to address a specific case and you are facing an issue could you please open a new issue and provide the following infos:

- What is the version of the controller-gen use by you? 
- Could you add the snipped of the code in the type files that you are using?
- Could you please add the issue face? 
- Could you please let us know what is the rule that would you like to apply?
 
Since it is open for a while without a reply for we know further information such as described above shows that you folks already figure out how to solve the problem. Then, shows fine we close this one as well. However, please feel free to ping us if you would like to re-open this issue and also to raise new ones.

**Closed by camilamacedo86** 2020-11-05 21:32 UTC
Labels: kind/support
