### ISSUE TITLE
Support pluralized Kinds

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes-sigs/kubebuilder#32] opened 2018-03-23 20:23 UTC
Generated files such as `zz_generated.kubebuilder.go` do not handle plural form kind name consistently. For instance, some informers call to `AppReplicas` kind via `.AppReplicases()`, but others via `.AppReplicass()`.

Furthermore, `k get redisreplicases` failed to list the objects.

Perhaps we can conform all kind names to singular form.

**Comment by pwittrock** [comment] 2018-04-03 03:12
Thanks for finding this.  The client gen code appears to improperly pluralize Kinds into resources simply by looking at the final character to see if it is an s - e.g. Fish -> Fishes, Children -> Childrens, Replicas -> Replicases.  I can work around this.

**Comment by pwittrock** [comment] 2018-04-03 03:35
It actually seems to use this for doing pluralization :(

https://github.com/kubernetes/gengo/blob/3b2d54029f5c97ae1ac22c7dfb9186854c253bbb/namer/plural_namer.go#L36

**Comment by pwittrock** [comment] 2018-04-03 03:40
The root of the issue is that https://github.com/kubernetes/code-generator doesn't support pluralized kinds.  This means that the names that the client generates will be incorrect.  My advice is to keep your Kinds singular - e.g. either `AppReplicaSet` or `AppReplica`.

**Comment by crimsonfaith91** [comment] 2018-04-03 03:51
@pwittrock Thanks for resolving my doubt! Appreciate it. :)

**Closed** 2018-04-03 16:34 UTC
