### ISSUE TITLE
CRD short names are overwritten by `make manifests`

### ISSUE THREAD

**Issue by astraw99** [kubernetes-sigs/kubebuilder#3103] opened 2022-11-29 14:33 UTC
### What broke? What's expected?

In the crd/bases/xxx.yaml，the default generated CRD yaml not include `shortNames` and `categories`, like:
```
spec:
  group: example.com
  names:
    kind: Demo
    listKind: DemoList
    plural: demos
    singular: demo
    categories: # will be overwritten
      - demo
    shortNames: # will be overwritten
      - de
  scope: Namespaced
  versions:
  - name: v1beta1
```
After `make manifests`, the `shortNames` and `categories` will be overwritten.

### Reproducing this issue

1. Create API, then `make manifests`;
2. Modify the crd/bases/xxx.yaml with `shortNames` and `categories` like above;
3. Then `make manifests` again, will reproduce this issue.

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.7.0", KubernetesVendor:"1.24.1", GitCommit:"3bfc84ec8767fa760d1771ce7a0cb05a9a8f6286", BuildDate:"2022-09-20T17:21:57Z", GoOs:"darwin", GoArch:"amd64"}

**Comment by camilamacedo86** [comment] 2022-11-29 14:55
Hi @astraw99, 

By looking into the steps :  

> Create API, then make manifests;
> Modify the crd/bases/xxx.yaml with shortNames and categories like above;
> Then make manifests again, will reproduce this issue.

You are changing the yaml directed. However, the specs are built from the API definition ( golang code ). So that is not a bug, you need to change your code to be able to generate other values in the manifests.

Example: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3-with-deploy-image/api/v1alpha1/busybox_types.go#L37

Also, I'd like to encourage you check out the plugin doc:
And then, try to create an example with to check the code for better understand how you should/can develop the solutions. https://book.kubebuilder.io/plugins/deploy-image-plugin-v1-alpha.html

On top of that, I'd like to recommend you read the [Tutorial: Building CronJob](https://book.kubebuilder.io/cronjob-tutorial/cronjob-tutorial.html#tutorial-building-cronjob) at least to have a better understand.

Closing this one as support and sorted out.
Feel free to re-open or raise new ones if you see required.
Closing this one

**Closed by camilamacedo86** 2022-11-29 14:55 UTC
Labels: kind/bug

**Comment by astraw99** [comment] 2022-11-29 15:10
Maybe I missed something here.
A normal field is added from the `xxx_types.go`, but here just want to know how to add the CRD short names?
Or which kubebuilder marker is used to achieve it?
