### ISSUE TITLE
init --controller-only clobbers my Gopkg.toml

### ISSUE THREAD

**Issue by grantr** [kubernetes-sigs/kubebuilder#263] opened 2018-06-12 23:30 UTC
I want to add kubebuilder controllers to my existing project which already has a `Gopkg.toml` file. When I run `kubebuilder init --controller-only`, my `Gopkg.toml` is replaced by a new one generated by kubebuilder. Kubebuilder's `Gopkg.toml` doesn't include any of my dep directives. Now I have to carefully merge the two files (assuming I had committed the previous one).

Ideally this command would generate code and tell me to run `dep ensure` after it's done. Dep should be able to vendor any kubebuilder packages imported by the generated code.

**Comment by pwittrock** [comment] 2018-06-13 16:18
@grantr If you just want the controller libraries, we are moving them out so they can be consumed separately from the tools: https://github.com/kubernetes-sigs/controller-runtime.  See https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg for docs.

**Comment by droot** [comment] 2018-06-14 00:10
>Ideally this command would generate code and tell me to run dep ensure after it's done. Dep should be able to vendor any kubebuilder packages imported by the generated code.

We thought about that as well. We wanted to pin the dependencies for Kubebuilder generated projects to ensure reproducibility of the deps in the generated project. Also, we have seen k8s dependencies don't play very well with the `dep` tool if you don't specify the `overrides` or `constraints` well.

**Comment by pwittrock** [comment] 2018-06-14 03:07
@grantr the reason we write the Gopkg.toml is so `dep` that all users are working with the same set of shared dependencies instead of a bespoke set that `dep` decided to grab.  On many occasions `dep` will not provide a set of dependencies that function together.

**Comment by droot** [comment] 2018-07-24 04:48
>I want to add kubebuilder controllers to my existing project which already has a Gopkg.toml file. When I run kubebuilder init --controller-only, my Gopkg.toml is replaced by a new one generated by kubebuilder. Kubebuilder's Gopkg.toml doesn't include any of my dep directives. Now I have to carefully merge the two files (assuming I had committed the previous one).
Correct workflow for this use-case would be to start with a new project (initialized with Kubebuilder) and then use user-managed-deps section in generated `Gopkg.toml` file for project specific dependencies.

Closing this issue. @grantr pl. re-open this issue if you think the suggested workflow doesn't address your use case.

**Closed by droot** 2018-07-24 04:48 UTC

**Comment by grantr** [comment] 2018-07-24 16:50
:+1: https://github.com/kubernetes-sigs/controller-runtime addresses this use case.
