### ISSUE TITLE
role.yaml doesn't contain all CRDs, and "make" nukes any fixes

### ISSUE THREAD

**Issue by jwatte** [kubernetes-sigs/kubebuilder#4024] opened 2024-07-18 03:40 UTC
### What broke? What's expected?

Create a new operator project.
Add two separate CRDs to the project.
Note that the generated config/role.yaml only generates RBAC rules for one of them.
Update config/role.yaml to add the other CRD type and notice the controller works again.
Now make some changes, and run "make" again.
Note that the generated config/role.yaml that you fixed, has now been overwritten, blowing away your fixes.

### Reproducing this issue

Add two CRDs to a project. Notice that role.yaml only authorizes one of them.

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"4.1.0", KubernetesVendor:"1.27.1", GitCommit:"de1cc60900b896b2195e403a40c976a892df4921", BuildDate:"2024-07-05T09:07:42Z", GoOs:"darwin", GoArch:"arm64"}

### PROJECT version

version: "3"

### Plugin versions

```yaml
layout:
- go.kubebuilder.io/v4
```

### Other versions

go version go1.22.5 darwin/arm64
sigs.k8s.io/controller-runtime v0.18.4

kubectl:
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.6-gke.1254000

**Comment by camilamacedo86** [comment] 2024-07-18 05:05
HI @jwatte,

I replied this one here: https://github.com/kubernetes-sigs/kubebuilder/discussions/4023#discussioncomment-10080039

See that we create a new project, scaffold a lot of APIs and we generate the rules for them as part of our tests to allow we merge each PR.

Then, as you can see the roles are generated as should be, for example you can see the rbac config for testdata/project-v4 with the ApiGroup for ALL CRDs generated with the tool: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v4/config/rbac/role.yaml

Then, regards:

> Note that the generated config/role.yaml that you fixed, has now been overwritten, blowing away your fixes.

⚠️ You should NOT update the roles manually. Yes, they will be overwritten when you run the make commands and that is the expected behaviour. You should use the tool to generate the APIs and update [markers](https://book.kubebuilder.io/reference/markers) to allow controller-gen properly generate the roles instead. Please, see the details and explanations shared with you in https://github.com/kubernetes-sigs/kubebuilder/discussions/4023#discussioncomment-10080039 as the suggested documentations.

I hope that helps you out. 
If you need please feel free to open other issues. However, I am closing this one as no bug since it is the expected behaviour and we can check in the result of our samples updated and validated automatically for each PR that all is working well as expected.

**Closed by camilamacedo86** 2024-07-18 05:05 UTC
Labels: kind/bug

**Comment by jwatte** [comment] 2024-07-19 04:29
The issue seems to be that the comments generated for kubebuilder weren't attached to the actual method in the controller scaffold.
Once I remove the empty space and put them right before the Reconcile() method, the annotations are properly applied.

What's weird is that when I attempted to reproduce this, the file was properly generated with both types.
I wonder if this is due to some local vscode formatting setting or something -- it was very clearly repeatable in the original project.

Hopefully this bug will remain on the internet if someone else runs into the same thing, and they'll find the reason here!

**Comment by camilamacedo86** [comment] 2024-07-19 05:04
HI @jwatte,

Thank you for your input.

> What's weird is that when I attempted to reproduce this, the file was properly generated with both types.
I wonder if this is due to some local vscode formatting setting or something -- it was very clearly repeatable in the original project.

If you find anyway to reproduce then, please let us know.
In this case, create an issue with the steps and then we can look on it. 

Thank you again for your collaboration.
