### ISSUE TITLE
ServiceMonitor template seems to contain invalid spec for kubectl 1.17+

### ISSUE THREAD

**Issue by storey247** [kubernetes-sigs/kubebuilder#1352] opened 2020-02-05 09:49 UTC
Using latest version of kubectl (v1.17.2), to apply the generated yaml for the controller, the client side validation outputs the following error regarding the ServiceMonitor YAML that gets generated:

```
error: error validating "./some/path/to/deployment": error validating data:
ValidationError(ServiceMonitor.spec.selector): unknown field "control-plane" in com.coreos.monitoring.v1.ServiceMonitor.spec.selector; 
if you choose to ignore these errors, turn validation off with --validate=false
```

This isn't an issue pre v1.17 so i believe that while the `ServiceMonitor` works if the validation is disabled.

I am guessing that the template being used for the scaffold of the ServiceMonitor is incorrect.

* go version: `go1.13.1 darwin/amd64` 
* kubebuilder version (`kubebuilder version`) and scaffolding version: `2`
* controller-runtime version (check your `go.mod` file): `sigs.k8s.io/controller-runtime v0.4.0`
* controller-tools version: `sigs.k8s.io/controller-tools v0.2.4`
* Kubernetes & kubectl versions: `v1.17.2`

/kind bug

**Comment by camilamacedo86** [comment] 2020-02-08 01:46
Hi @storey247, 

If we add in the first comment of the PR Closes: #<issue-number> then, the issue is closed when it gets merged. However, since it was not made. Could you please close this now that the fix is merged?

**Comment by camilamacedo86** [comment] 2020-02-08 01:49
Closing this one since the solution was merged.
Please, feel free to re-open if you see that it is required. 
/close

**Closed by camilamacedo86** 2020-02-08 01:49 UTC
Labels: kind/bug
