### ISSUE TITLE
Non-namespaced resource CRD gets generated as scope: Namespaced

### ISSUE THREAD

**Issue by bwarminski** [kubernetes-sigs/kubebuilder#322] opened 2018-07-20 01:35 UTC
Command Issued:

```
kubebuilder create api --group bigthicket --kind EphemeralEnvironment --namespaced false --version v1alpha1
```

Resulting crd:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: ephemeralenvironments.bigthicket.localytics.com
spec:
  group: bigthicket.localytics.com
  names:
    kind: EphemeralEnvironment
    plural: ephemeralenvironments
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
      type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
```

Expected `scope: Cluster`

**Comment by droot** [comment] 2018-07-20 17:19
@fanzhangio Can you pl. take a look this one ?

**Comment by fanzhangio** [comment] 2018-08-02 06:36
I found the root cause. It's because `crd generator` in v1 mixed `internal/parser` in v0, which depends on `+genclient:nonNamespaced` annotationns, calling IsNonNamespaced() for validation.

This should be fixed by:
1) Workaround. 
2) Refactor crd generator on the heritage codes

**Comment by fanzhangio** [comment] 2018-08-03 00:08
@bwarminski Thanks for your feedback. Please use `--namespaced=false` instead.

**Comment by fanzhangio** [comment] 2018-08-16 00:35
@bwarminski Does it solve your issue? Please let me know if you need any help.

**Comment by droot** [comment] 2018-08-21 17:30
closing this issue. pl. re-open if this is still an issue.

**Closed by droot** 2018-08-21 17:30 UTC

**Comment by lluunn** [comment] 2019-02-28 18:17
Is there a way to make a CRD cluster scope after `kubebuilder create api` is done? I didn't pass in `
--namespaced=false`

**Comment by lluunn** [comment] 2019-02-28 18:23
answering myself:
add `// +genclient:nonNamespaced` comment to my type definition

**Comment by akrausesap** [comment] 2019-05-27 11:31
unfortunately does not work for me anymore with KubeBuilderVersion:"2.0.0-alpha.2". Neither `// +genclient:nonNamespaced` nor `kubebuilder create api --group bigthicket --kind EphemeralEnvironment --namespaced false --version v1alpha1`or  `--namespaced=false` generated non-namespaced CRD. Please help

**Comment by skeres** [comment] 2024-08-05 06:47
5 years later ... Thank you, the solution of @fanzhangio works for me
But please :smile:  correct this bug, --namespaced false ( without '=' ) should work.  Lost 3 hours trying to enforce cluster scope ...
`
kubebuilder version
Version: main.version{KubeBuilderVersion:"4.1.1", KubernetesVendor:"1.30.0", GitCommit:"e65415f10a6f5708604deca089eee6b165174e5e", BuildDate:"2024-07-23T07:11:14Z", GoOs:"linux", GoArch:"amd64"}

go version
go version go1.22.5 linux/amd64
`
