### ISSUE TITLE
Handle --group flag for core types when empty string is provided

### ISSUE THREAD

**Issue by kopiczko** [kubernetes-sigs/kubebuilder#2162] opened 2021-04-28 15:31 UTC
### What broke? What's expected?

Specifying `--group=""` for a core type is confusing. When I ran it with `--group="" --version=v1 --kind=Pod` I expected to have it handled as a core type. To make it work for a core type I have to set `--gourp="core"` which is not obvious.

### Reproducing this issue

This is ok:

```
$ kubebuilder create api --group "core" --version "v1" --kind "Pod" --resource=false --controller=false
Writing scaffold for you to edit...
Update dependencies:
$ go mod tidy

$ git --no-pager diff
diff --git a/PROJECT b/PROJECT
index 1ecd802..67f6e5a 100644
--- a/PROJECT
+++ b/PROJECT
@@ -3,4 +3,9 @@ layout:
 - go.kubebuilder.io/v3
 projectName: kubebuilder-test
 repo: github.com/kopiczko/kubebuilder-test
+resources:
+- group: core
+  kind: Pod
+  path: k8s.io/api/core/v1
+  version: v1
 version: "3"
```

This is **not** ok:

```
$ kubebuilder create api --group "" --version "v1" --kind "Pod" --resource=false --controller=false
Writing scaffold for you to edit...
Update dependencies:
$ go mod tidy

$ git --no-pager diff
diff --git a/PROJECT b/PROJECT
index 1ecd802..1755c7c 100644
--- a/PROJECT
+++ b/PROJECT
@@ -3,4 +3,8 @@ layout:
 - go.kubebuilder.io/v3
 projectName: kubebuilder-test
 repo: github.com/kopiczko/kubebuilder-test
+resources:
+- domain: my-domain.com
+  kind: Pod
+  version: v1
 version: "3"
```

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"3.0.0-rc.0", KubernetesVendor:"1.19.2", GitCommit:"90fe4124c4c6965c6bfac63339888956952cda90", BuildDate:"2021-04-08T17:36:28Z", GoOs:"darwin", GoArch:"amd64"}

### PROJECT version

v3

### Plugin versions

```yaml
layout:
- go.kubebuilder.io/v3
```
```


### Other versions

_No response_

### Extra Labels

_No response_

**Comment by jmrodri** [comment] 2021-05-04 18:08
This seems like a duplicate of this issue #1999

**Comment by camilamacedo86** [comment] 2021-05-04 18:16
Hi @kopiczko, 

It is not officially supported now and it seems a desirable RFE. I think we can close this one as a duplicate. However, please feel free to push a PR with your ideas and/or work in on in the  #1999. 

If you think that should be re-open and cannot be closed as duplicated please let us know either.

**Closed by camilamacedo86** 2021-05-04 18:16 UTC
Labels: kind/bug
