### ISSUE TITLE
make generate cannot pin the  version of the controller-gen

### ISSUE THREAD

**Issue by jiachengxu** [kubernetes-sigs/kubebuilder#909] opened 2019-08-02 11:14 UTC
In the current Makefile generated by kubebuilder:
```
controller-gen:
ifeq (, $(shell which controller-gen))
    go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.0-beta.4
CONTROLLER_GEN=$(GOBIN)/controller-gen
else
CONTROLLER_GEN=$(shell which controller-gen)
endif
```
This can not override the version of the controller-gen to v0.2.0-beta.4 if an outdated version of `controller-gen` exists in the  `$GOPATH/bin`, this may lead to different behaviors when generating the code.

Also, checking the version of `controller-gen` is impossible, since there is no `version` flag in `controller-gen`.
Ref: https://github.com/kubernetes-sigs/controller-tools/issues/259

/kind bug

**Comment by flameshimmer** [comment] 2019-08-02 20:03
I am running into the exactly the same issue. Anyone please help?

**Comment by jiachengxu** [comment] 2019-08-02 20:32
Hi @flameshimmer , you can just remove the controller-gen binary in your path then do make generate to use the correct version

**Comment by DirectXMan12** [comment] 2019-08-05 21:04
this is fairly intentional -- it's intended that you use whatever's on your path, to allow you to specify custom versions of controller-gen, or to download pre-compiled versions.

**Comment by DirectXMan12** [comment] 2019-08-05 21:05
I'm not sure what the right solution is here.  If we had a `--version` flag we could warn at least.

**Comment by mcristina422** [comment] 2019-08-14 19:11
I've run into issues where different collaborators end up with different versions. Having a `--version` flag would at least help us detect this. Additionally the `go get` in the makefile is modifying the go.mod and that isn't desirable. 

But in the meantime I think my team will just build a docker container for controller-gen and run it with volume mounts to generate the manifests 


```Makefile
controller-gen:
	docker build -t controller_gen -f Dockerfile.controller_gen .
```

```Dockerfile
FROM golang:1.12.8 as builder

WORKDIR /workspace

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.0-beta.5

ENTRYPOINT ["/go/bin/controller-gen"]
```

**Comment by DirectXMan12** [comment] 2019-08-15 22:59
we've got an open issue for the version flag, and a way to implement it, so it should come eventually (it's kubernetes-sigs/controller-tools#259)

**Comment by adinunzio84** [comment] 2019-08-21 19:26
Could adding a `tools.go` file to the hack directory solve the issue of different people ending up with different versions? (It would pin the dependency to the `go.mod` file).
Not sure if it's still a best practice to do this: golang/go#25922 (see "What did you do" section).

**Comment by kron4eg** [comment] 2019-08-24 22:00
Here's what I did to fix this.

```golang
# hack/tools.go
// +build tools

package tools

import (
	_ "sigs.k8s.io/controller-tools/cmd/controller-gen"
)
```

```makefile
# Makefile

CONTROLLER_GEN=go run sigs.k8s.io/controller-tools/cmd/controller-gen

manifests: ## Generate manifests e.g. CRD, RBAC etc.
	$(CONTROLLER_GEN) $(CRD_OPTIONS) rbac:roleName=manager webhook paths="./..." output:crd:artifacts:config=config/crd/bases
generate: ## Generate code
	$(CONTROLLER_GEN) object:headerFile=./hack/boilerplate.go.txt paths=./api/...
```

hack/tools.go help go mods to pin controller-tools to specific version, and `go run` automatically run whatever version is in go.mod. This is to ensure we take controller-tools under control (pun intended).

```bash
$ grep controller-tool go.mod
        sigs.k8s.io/controller-tools v0.2.0
```


This part:

```makefile
controller-gen:
ifeq (, $(shell which controller-gen))
    go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.0-beta.4
CONTROLLER_GEN=$(GOBIN)/controller-gen
else
CONTROLLER_GEN=$(shell which controller-gen)
endif
```

is removed entirely.

P.S.
One last nice to have

```makefile
# Makefile
export GOFLAGS?=-mod=readonly
```

This ensures no surprises during the build.

**Comment by DirectXMan12** [comment] 2019-09-03 14:33
The only reason I'm hesitant about that is that it adds a hard requirement on CT and it's deps to the project as build deps, which I'm not sure is something we want to do.

**Comment by DirectXMan12** [comment] 2019-09-03 14:33
at least not as long as we still have non-multi-version-compatible deps coming out of kubernetes.

**Comment by adinunzio84** [comment] 2019-09-03 15:42
If you have `//+build tools` in the `tools.go` file, IIUC, it won't be a build dependency (though it will be listed in go.mod and go.sum). Go just uses the go.mod file as a "guide" on dependencies but will only compile and link the code that's used (again, IIUC). That way it's not totally necessary for strict forwards and backwards compatibility for controller-tools, since it would be set in the go.mod and go.sum.

Would be nice if there were a "dev" dependencies section in those files though.

**Comment by DirectXMan12** [comment] 2019-09-03 17:32
The problem is that, basically, you want to install controller-tools in a way that means there aren't issues if its dependencies conflict in an incompatible way with controller-runtime's or the projects, for whatever reason.  This is technically possible now, since you can just run `go get sigs.k8s.io/controller-tools/cmd/controller-gen` outside a project, and get the binary installed.

Adding a dev dependencies with `//+build tools` means that if controller-tools ever had conflicting k8s deps with controller-runtime, the project in question, etc, we'd run into issues (which has happened in the past).  Normally with Go modules it wouldn't be an issue, since major version bumps change import paths, but k8s deps don't do this (yet), so you can't have two major versions side-by-side.

**Comment by camilamacedo86** [comment] 2019-11-14 14:38
Hi @DirectXMan12 and @jiachengxu, 

We added a Makefile target `make generate-setup` in order to solve it. So, could we not close this one? Now devs can just run `make generate` and the correct version will be used always. WDYT?

**Comment by camilamacedo86** [comment] 2020-05-07 22:27
Hi folks, 

I understand that intentionally we use a specific dep version which was tested. However, if users would like they are able to customize the Makefile as their wish and in this way change the version used by default. 

So, I am not sure if has something that we. should or still missing to address here. IHMO I think we can close this one. @DirectXMan12 @mengqiy has any reason for still keeping it open? Do you see anything that should be addressed here?

**Comment by camilamacedo86** [comment] 2020-05-09 11:06
Hi folks, 

I understand that intentionally we use a specific dep version which was tested. However, if users would like they are able to customize the Makefile in their project as their wish and in this way change the version used by default. ( See the comment made above as well https://github.com/kubernetes-sigs/kubebuilder/issues/909#issuecomment-527559888 )However, it is up to the user to ensure its compatibility with their project. 

Also, we have a proposed solution to improve it and add the version in the PROJECT file. See: https://github.com/kubernetes-sigs/kubebuilder/issues/1351

So, I am not sure if has something that should still be missing to address here. In this way, I am closing this one since the latest interaction was on 3 Sep 2019 and shows that has no action that we could take further here and all is covered. However, please feel free to re-open if you think that some requirement still needs to be addressed with.

/close

**Closed** 2020-05-09 11:06 UTC
Labels: kind/bug
