### ISSUE TITLE
versionPattern should be more flexible to allow internal versions

### ISSUE THREAD

**Issue by robzienert** [kubernetes-sigs/kubebuilder#3739] opened 2024-01-24 19:25 UTC
### What broke? What's expected?

The [versionPattern](https://github.com/kubernetes-sigs/kubebuilder/blob/165af70e87848677a039cd0cd87cc67c545d983c/pkg/model/resource/gvk.go#L28) enforced by kubebuilder requires all CRD versions to start with a `v`, however this makes usage of an internal version confusing (e.g. creating a `v0`) where an `internal` or `__internal` version would communicate intent more clearly; `__internal` is even used within the [core Kubernetes codebase](https://github.com/kubernetes/apimachinery/blob/f14778da5523847e4c07346e3161a4b4f6c9186e/pkg/runtime/interfaces.go#L30).

What I'd like to see is the `versionPattern` relaxed to make an allowance for internal versions, something like so:

Before: 

```go
const (
	versionPattern = "^v\\d+(?:alpha\\d+|beta\\d+)?$"
)
```

After:

```go
const (
	versionPattern = "^(?:__internal|v\\d+(?:alpha\\d+|beta\\d+)?)$"
)

```

Doing so would be additive and not break any of the existing uses.

### KubeBuilder (CLI) Version

v3.12.0

**Comment by camilamacedo86** [comment] 2024-01-25 11:39
Hi @robzienert 

Thank you for raising this one. 
We should do the same k8s validation.

In this case, I think it probably should be checked by: [func IsDNS1035Label(value string) []string {](https://github.com/kubernetes-sigs/kubebuilder/blob/165af70e87848677a039cd0cd87cc67c545d983c/pkg/internal/validation/dns.go#L90-L93)

However, we need to TBD what the right k8s validation is and use the same.

**Comment by camilamacedo86** [comment] 2024-02-16 03:00
Hi @robzienert 

My sincere apologies, I oversight this one. 
The PR https://github.com/kubernetes-sigs/kubebuilder/pull/3742 introduced an regression.

In Kubernetes Custom Resource Definitions (CRDs), Kind names must not include spaces, special characters (e.g., @, #, $, %, &, *), or punctuation marks. They should strictly adhere to CamelCase format, starting with an uppercase letter and not violating the general programming identifier rules (e.g., no starting with numbers, no reserved words). This ensures compatibility with Kubernetes API and client code generation tools.

The [func IsDNS1035Label(value string) []string {](https://github.com/kubernetes-sigs/kubebuilder/blob/165af70e87848677a039cd0cd87cc67c545d983c/pkg/internal/validation/dns.go#L90-L93) is NOT accurated for this case. 

The correct one seems to be :

```
// IsDNS1123Subdomain tests for a string that conforms to the definition of a
// subdomain in DNS (RFC 1123).
func IsDNS1123Subdomain(value string) []string {
	return dns1123SubdomainConfig.check(value)
}
```

Therefore, to close this one we need change the validation like was done in the PR https://github.com/kubernetes-sigs/kubebuilder/pull/3742

However, to avoid we introduce and issue we should add more tests in the project to ensure that names like DNS will be allowed to be used.

**Comment by Sajiyah-Salat** [comment] 2024-03-04 04:17
@camilamacedo86 is this really a good first issue? I dont see the clear cut implementation to close this issue.

**Comment by Kavinjsir** [comment] 2024-06-14 07:18
> @camilamacedo86 is this really a good first issue? I dont see the clear cut implementation to close this issue.

@Sajiyah-Salat The code for implementation isn’t extensive, which makes it a good-first-issue.
However, since it’s marked as `priority/important-soon`, I've gone ahead and created a PR to progress: https://github.com/kubernetes-sigs/kubebuilder/pull/3986.
If you're still interested, would you be willing to help with the review? :)

**Closed** 2024-07-21 10:28 UTC
Labels: help wanted, good first issue, kind/bug, priority/important-soon
