### ISSUE TITLE
Optimize Marker's code generation coverage logic

### ISSUE THREAD

**Issue by cuisongliu** [kubernetes-sigs/kubebuilder#3495] opened 2023-07-13 06:00 UTC
### What do you want to happen?

When I execute kubebuilder create api --force , I found that the code of the main controller has been added repeatedly. Looking at marker.go, I found that there is only one position for the marker. It may be better if we optimize it to the beginning.

```
//+kubebuilder:scaffold:builder:begin
      if err = (&controller.SettingReconciler{
		MaxConcurrentReconciles: concurrent,
		RateLimiter:             utilcontroller.GetRateLimiter(rateLimiterOptions),
	}).SetupWithManager(mgr); err != nil {
		setupLog.Error(err, "unable to create controller", "controller", "Setting")
		os.Exit(1)
	}
//+kubebuilder:scaffold:builder:end
```

**Comment by camilamacedo86** [comment] 2023-07-14 06:43
Hi @cuisongliu,

Can you please let us know the steps performed, what do you expected to see and what are you seen instead?
Can you please confirm my understand over this one:

- You run kb create api [OPTIONS]
- Then, you run the same command with force again and the main.go was updated to add another call for the same controller? Is that the issue?

**Comment by cuisongliu** [comment] 2023-07-14 08:56
using kubebuilder v3.11.1
```
[16:50:39] [~/Workspaces/go/src/github.com/labring/kubebuilder4helm/tests/helm-project] git(main) 🔥 ❱❱❱ kubebuilder create api --group user --version v1beta1 --kind Setting  --force                    
Create Resource [y/n]
y
Create Controller [y/n]
y
Writing kustomize manifests for you to edit...
Writing scaffold for you to edit...
api/v1beta1/setting_types.go
api/v1beta1/groupversion_info.go
controllers/suite_test.go
controllers/setting_controller.go
Update dependencies:
$ go mod tidy
Running make:
$ make generate
mkdir -p /Users/cuisongliu/Workspaces/go/src/github.com/labring/kubebuilder4helm/tests/helm-project/bin
test -s /Users/cuisongliu/Workspaces/go/src/github.com/labring/kubebuilder4helm/tests/helm-project/bin/controller-gen && /Users/cuisongliu/Workspaces/go/src/github.com/labring/kubebuilder4helm/tests/helm-project/bin/controller-gen --version | grep -q v0.12.0 || \
        GOBIN=/Users/cuisongliu/Workspaces/go/src/github.com/labring/kubebuilder4helm/tests/helm-project/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.12.0
/Users/cuisongliu/Workspaces/go/src/github.com/labring/kubebuilder4helm/tests/helm-project/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
Next: implement your new API and generate the manifests (e.g. CRDs,CRs) with:
$ make manifests
[16:50:58] [cost 10.342s] kubebuilder create api --group user --version v1beta1 --kind Setting  --force                                                                                                                                             

[16:50:58] [~/Workspaces/go/src/github.com/labring/kubebuilder4helm/tests/helm-project] git(black) 🔥 ❱❱❱ kubebuilder create api --group user --version v1beta1 --kind Setting  --force 
Create Resource [y/n]
y
Create Controller [y/n]
y
Writing kustomize manifests for you to edit...
Writing scaffold for you to edit...
api/v1beta1/setting_types.go
api/v1beta1/groupversion_info.go
controllers/suite_test.go
controllers/setting_controller.go
Update dependencies:
$ go mod tidy
Running make:
$ make generate
/Users/cuisongliu/Workspaces/go/src/github.com/labring/kubebuilder4helm/tests/helm-project/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
Next: implement your new API and generate the manifests (e.g. CRDs,CRs) with:
$ make manifests

```

controller code:
```
	if err = (&controller.SettingReconciler{
		MaxConcurrentReconciles: concurrent,
		RateLimiter:             utilcontroller.GetRateLimiter(rateLimiterOptions),
	}).SetupWithManager(mgr); err != nil {
		setupLog.Error(err, "unable to create controller", "controller", "Setting")
		os.Exit(1)
	}
	if err = (&controller.SettingReconciler{
		MaxConcurrentReconciles: concurrent,
		RateLimiter:             utilcontroller.GetRateLimiter(rateLimiterOptions),
	}).SetupWithManager(mgr); err != nil {
		setupLog.Error(err, "unable to create controller", "controller", "Setting")
		os.Exit(1)
	}
	//+kubebuilder:scaffold:builder
```

**Comment by cuisongliu** [comment] 2023-07-14 08:57
I think if --force should be overwriting, not appending

**Comment by swastik959** [comment] 2023-07-17 06:22
@cuisongliu I think it already does overwrite . https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v3/scaffolds/internal/templates/controllers/controller.go#L55

**Comment by cuisongliu** [comment] 2023-07-17 09:02
> @cuisongliu I think it already does overwrite . https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v3/scaffolds/internal/templates/controllers/controller.go#L55


Looking at the code, the coverage is indeed marked, but when I execute it, append is actually generated. You can execute it and see. For the controller, it does not know the starting position, because the main.go is updated and not regenerated, which is equivalent to modifying the main.go code when creating the api. Not sure if I understand correctly.

https://github.com/kubernetes-sigs/kubebuilder/blob/5356022b3646acf371b4877276f9a431989cceeb/pkg/plugins/golang/v3/scaffolds/api.go#L107

**Comment by mjlshen** [comment] 2023-08-07 02:59
@cuisongliu I'm not able to reproduce what you're seeing, here's what I tried, let me know if you did something different:

```
mkdir 3495
go mod init github.com/mjlshen/3495
kubebuilder init --plugins go/v4 --domain example.com
kubebuilder create api --group user --version v1beta1 --kind Setting  --force
kubebuilder create api --group user --version v1beta1 --kind Setting  --force
```

The relevant part of `cmd/main.go` looks like (only one copy, not repeated):

```go
	if err = (&controller.SettingReconciler{
		Client: mgr.GetClient(),
		Scheme: mgr.GetScheme(),
	}).SetupWithManager(mgr); err != nil {
		setupLog.Error(err, "unable to create controller", "controller", "Setting")
		os.Exit(1)
	}
	//+kubebuilder:scaffold:builder
```

**Comment by camilamacedo86** [comment] 2023-08-30 06:43
Hi @cuisongliu,

 @mjlshen (thx a lot btw) could not either reproduce the scenario.
See that your issue might be a result of:

-  a) Customizations and changes in the default scaffold. be aware of: 

![Screenshot 2023-08-30 at 07 42 02](https://github.com/kubernetes-sigs/kubebuilder/assets/7708031/2cc7746f-7af3-4b40-8653-3971da7b62ac)

OR

- b) you are using an old version which has a bug

OR

- c) the markers are duplicated. 


 In this way, I hope that you do not mind that we will close this one.
However, feel free to re-open if you see that fits.

**Closed by camilamacedo86** 2023-08-30 06:43 UTC
Labels: triage/needs-information, kind/feature
