### ISSUE TITLE
Internal Error while trying to run the CronJob example

### ISSUE THREAD

**Issue by gaodan-fang** [kubernetes-sigs/kubebuilder#1627] opened 2020-08-06 14:12 UTC
/triage support
Hey i am a newbee to kube operators and i keep getting this erros while running the controller locally through `make run ENABLE_WEBHOOKS=false`
My go version: `go version go1.14.5 darwin/amd64`
My kubenets version: `Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0"`
```
2020-08-05T14:27:55.399-0400	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": ":8080"}
2020-08-05T14:27:55.399-0400	INFO	setup	starting manager
2020-08-05T14:27:55.500-0400	INFO	controller-runtime.manager	starting metrics server	{"path": "/metrics"}
2020-08-05T14:27:55.500-0400	INFO	controller-runtime.controller	Starting EventSource	{"controller": "cronjob", "source": "kind source: /, Kind="}
E0805 14:27:55.575045   47201 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1alpha1.CronJob: Get "https://127.0.0.1:32780/apis/batch.tutorial.kubebuilder.io/v1alpha1/cronjobs?limit=500&resourceVersion=0": stream error: stream ID 75; INTERNAL_ERROR
E0805 14:27:55.587087   47201 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1alpha1.CronJob: Get "https://127.0.0.1:32780/apis/batch.tutorial.kubebuilder.io/v1alpha1/cronjobs?limit=500&resourceVersion=0": stream error: stream ID 77; INTERNAL_ERROR
E0805 14:27:57.881064   47201 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1alpha1.CronJob: Get "https://127.0.0.1:32780/apis/batch.tutorial.kubebuilder.io/v1alpha1/cronjobs?limit=500&resourceVersion=0": stream error: stream ID 79; INTERNAL_ERROR
E0805 14:28:03.291456   47201 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1alpha1.CronJob: Get "https://127.0.0.1:32780/apis/batch.tutorial.kubebuilder.io/v1alpha1/cronjobs?limit=500&resourceVersion=0": stream error: stream ID 81; INTERNAL_ERROR
```
Appreciate if anyone could help

**Comment by varshaprasad96** [comment] 2020-08-12 05:35
I'm facing a similar error too while following the multi-version API example as given in kubebuilder book, with `client-go` version being `0.17.2`. 

The error seems to be similar:
```
E0812 04:17:58.780638       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1.CronJob: Get https://10.96.0.1:443/apis/batch.tutorial.kubebuilder.io/v1/cronjobs?limit=500&resourceVersion=0: stream error: stream ID 365; INTERNAL_ERROR
E0812 04:17:59.794347       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1.CronJob: Get https://10.96.0.1:443/apis/batch.tutorial.kubebuilder.io/v1/cronjobs?limit=500&resourceVersion=0: stream error: stream ID 371; INTERNAL_ERROR
```

For reference:
go version: `go version go1.13.8 darwin/amd64`
kubernetes version: `"v1.16.7"`

Would be helpful to know a fix or workaround for this error.

**Comment by varshaprasad96** [comment] 2020-08-13 16:31
Not sure of the exact cause, but this error did not resurface after using the KB binary built from master.

**Comment by gaodan-fang** [comment] 2020-08-13 18:38
@varshaprasad96 that sounds great, i will test it

**Comment by lukasfrank** [comment] 2020-08-27 15:08
I was facing a similar issue: 
```
E0827 11:10:23.717423   78260 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list 
```

For me it worked to use the ``k8s server`` version ``v1.16.12``

**Comment by gabbifish** [comment] 2020-09-18 08:12
Hello! I'm using kubernetes version `v1.17.0` and haven't been able to reproduce this issue on that version. Have you been able to successfully run `make install & make run`? Has upgrading your kubernetes version helped you?

**Comment by camilamacedo86** [comment] 2020-10-26 12:07
Hi @gaodan-fang, 

I am unable to reproduce your issue as well. However, see that the code of the projects used in the docs was very outdated and we update them in the PR:  https://github.com/kubernetes-sigs/kubebuilder/pull/1632. However, see that we still with issues in these projects that needs be fixed. I'd like to suggest to you follow up https://github.com/kubernetes-sigs/kubebuilder/issues/1544 and re-check it when this one is closed. 

Since the specific issue raised here shows that is no longer reproduced and we have the https://github.com/kubernetes-sigs/kubebuilder/issues/1544 tracked to address another scenario in the book code shows fine we close this one. However, please feel free to ping us if you think that it should be re-opened as to raise new issues. 

Thank you for your collaboration.

**Closed by camilamacedo86** 2020-10-26 12:07 UTC
Labels: kind/support
