### ISSUE TITLE
Unable to use +kubebuilder:validation:UniqueItems=true

### ISSUE THREAD

**Issue by npnwdev** [kubernetes-sigs/kubebuilder#3300] opened 2023-03-15 18:35 UTC
### What broke? What's expected?

I included marker `+kubebuilder:validation:UniqueItems=true` on a field in my CRD and when applied on k8s, received the below exception. 

	// +kubebuilder:validation:UniqueItems=true
	Names []string `json:"names,omitempty" protobuf:"bytes,3,opt,name=names"`

	// +kubebuilder:validation:UniqueItems=true
	Places []string `json:"places,omitempty" protobuf:"bytes,4,opt,name=places"`

user@host:~/go/src/myrepo/path$ kubectl apply -f config/crd/bases/group.domain.net_object.yaml 
The CustomResourceDefinition "object.group.domain.net" is invalid: 
* spec.validation.openAPIV3Schema.properties[status].properties[names].uniqueItems: Forbidden: uniqueItems cannot be set to true since the runtime complexity becomes quadratic
* spec.validation.openAPIV3Schema.properties[status].properties[places].uniqueItems: Forbidden: uniqueItems cannot be set to true since the runtime complexity becomes quadratic

### Reproducing this issue

Add validation marker `// +kubebuilder:validation:UniqueItems=true` on an array field

Env:
KubeBuilderVersion:"3.9.0", KubernetesVendor:"1.26.0", GitCommit:"26f605e889b2215120f73ea42b081efac99f5162", BuildDate:"2023-01-16T17:21:30Z", GoOs:"linux", GoArch:"amd64"

### KubeBuilder (CLI) Version

3.9.0

### PROJECT version

3

### Plugin versions

```yaml
layout:
- go.kubebuilder.io/v3
```

### Other versions

go version:
 go1.19.4 linux/amd64

kubectl version:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:30Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by xiao-jay** [comment] 2023-03-19 06:09
@npnwdev 
In [contributors/design-proposals/customresources-validation.md](https://github.com/kubernetes/community/pull/708#discussion_r121948264):
> +	Description          string                     `json:"description,omitempty"`
>+	Type                 StringOrArray              `json:"type,omitempty"`
>+	Format               string                     `json:"format,omitempty"`
>+	Title                string                     `json:"title,omitempty"`
>+	Default              interface{}                `json:"default,omitempty"`
>+	Maximum              *float64                   `json:"maximum,omitempty"`
>+	ExclusiveMaximum     bool                       `json:"exclusiveMaximum,omitempty"`
>+	Minimum              *float64                   `json:"minimum,omitempty"`
>+	ExclusiveMinimum     bool                       `json:"exclusiveMinimum,omitempty"`
>+	MaxLength            *int64                     `json:"maxLength,omitempty"`
>+	MinLength            *int64                     `json:"minLength,omitempty"`
>+	Pattern              string                     `json:"pattern,omitempty"`
>+	MaxItems             *int64                     `json:"maxItems,omitempty"`
>+	MinItems             *int64                     `json:"minItems,omitempty"`
>+	// disable uniqueItems for now because it can cause the validation runtime
>+	// complexity to become quadratic.


If you want to use ,you may can run `--feature-gates=CustomResourceValidation=false`

Finally: you can read the discuss in `https://groups.google.com/g/kubernetes-sig-api-machinery-proposals/c/Rn7QaNojCO4/m/gJY1nze7AAAJ`

**Comment by xiao-jay** [comment] 2023-03-25 04:28
@camilamacedo86 maybe this issue can close?This is not a bug.

**Comment by camilamacedo86** [comment] 2023-04-22 08:43
I am closing this one based on the above comment. However, please feel free to re-open it and let us know if you see that still a bug or if you need help with it.

**Closed by camilamacedo86** 2023-04-22 08:43 UTC
Labels: kind/bug
