### ISSUE TITLE
Error: unable to load the configuration: unable to read "PROJECT" file: read PROJECT: is a directory get error 

### ISSUE THREAD

**Issue by 631068264** [kubernetes-sigs/kubebuilder#2666] opened 2022-04-30 14:42 UTC
### What broke? What's expected?

downlowd from https://github.com/kubernetes-sigs/kubebuilder/releases/download/v3.4.0/kubebuilder_darwin_amd64

follow it https://book.kubebuilder.io/quick-start.html#installation to install

use `kubebuilder version` get same error

```sh
➜  ~ kubebuilder completion zsh
Error: unable to load the configuration: unable to read "PROJECT" file: read PROJECT: is a directory
Usage:
  kubebuilder [flags]

Examples:
The first step is to initialize your project:
    kubebuilder init [--plugins=<PLUGIN KEYS> [--project-version=<PROJECT VERSION>]]

<PLUGIN KEYS> is a comma-separated list of plugin keys from the following table
and <PROJECT VERSION> a supported project version for these plugins.

                        Plugin keys | Supported project versions
------------------------------------+----------------------------
          base.go.kubebuilder.io/v3 |                          3
   declarative.go.kubebuilder.io/v1 |                       2, 3
               go.kubebuilder.io/v2 |                       2, 3
               go.kubebuilder.io/v3 |                          3
 kustomize.common.kubebuilder.io/v1 |                          3

For more specific help for the init command of a certain plugins and project version
configuration please run:
    kubebuilder init --help --plugins=<PLUGIN KEYS> [--project-version=<PROJECT VERSION>]

Default plugin keys: "go.kubebuilder.io/v3"
Default project version: "3"


Flags:
  -h, --help                     help for kubebuilder
      --plugins strings          plugin keys to be used for this subcommand execution
      --project-version string   project version (default "3")

2022/04/30 22:34:37 unable to load the configuration: unable to read "PROJECT" file: read PROJECT: is a directory
```

### KubeBuilder (CLI) Version

3.4.0

**Comment by camilamacedo86** [comment] 2022-05-04 21:09
Hi @631068264, 

Are using a go version >= 1.17 and  < 1.18 ?
Are you scaffolding the projects in a directory where the tool will have permission to write? 

I am unable to reproduce this one. Could you please let us know more about ?

**Comment by 631068264** [comment] 2022-05-05 08:14
@camilamacedo86 ,

go version go1.17.6 darwin/amd64

OSX 12.3.1


I just download it run it, remove it to `/usr/local/bin/kubebuilder` ,  and then run` kubebuilder version`  without creating any project or directory .

the cmd `create ` run very well just `version` get error

**Comment by camilamacedo86** [comment] 2022-05-05 10:50
Are you able to create new projects?
Are you able to: * In your GOPATH

```
mkdir test
cd test
kubebuilder init
```

?

**Comment by 631068264** [comment] 2022-05-05 12:46
<img width="622" alt="image" src="https://user-images.githubusercontent.com/8144089/166925618-87763ae9-8f62-49b1-9ee6-5683f9cb4f22.png">
`kubebuilder init`  is well

What is ` * In your GOPATH` mean?

**Comment by camilamacedo86** [comment] 2022-05-09 12:09
Hi @631068264,

I am unable to reproduce this issue:

```
$ kubebuilder_darwin_amd64 version
Version: main.version{KubeBuilderVersion:"3.3.0", KubernetesVendor:"1.23.1", GitCommit:"47859bf2ebf96a64db69a2f7074ffdec7f15c1ec", BuildDate:"2022-01-18T17:03:29Z", GoOs:"darwin", GoArch:"amd64"}

``` 

I was a bug in the past, so you might call an old binary instead of this version ( it probably is another place in your local env ) when you see this error. See https://github.com/kubernetes-sigs/kubebuilder/pull/2126 ( this fix was released with v3.0.0: https://github.com/kubernetes-sigs/kubebuilder/releases/tag/v3.0.0

> What is * In your GOPATH mean?

GOPATH is the path of your Golang local environment. Check your golang env. ($ go env)

I'd recommend you remove this bin from /usr/local/bin/kubebuilder and run the kubebuilder version it probably will still be called, and you probably have a kubebuilder CLI binary installed in another place. Then, remove the kubebuilder bin from all places ( you can check that by running kuebuilder version until it does not output command not found you have a bin installed in your local env ). After that try to re-install the latest version or this specific release.

**Comment by geetikabatra** [comment] 2022-05-16 15:44
I can confirm the issue. This is a recurring one, even with [v3.0.0](https://github.com/kubernetes-sigs/kubebuilder/releases/tag/v3.0.0)

**Comment by camilamacedo86** [comment] 2022-05-19 10:38
Hi @631068264, 

I tried to reproduce your scenario with the latest releases, and I am unable.
Note that we cannot ensure the version of the bin used with the tests made above. 

Another thing that calls my attention is that you are using GOVERSION="go1.18.1" ad it is not supported 
You **must** use go versions >= 1.17  < 1.18. 

Could you check if that might no be the root cause as well?

**Comment by camilamacedo86** [comment] 2022-05-22 10:50
I am closing this one since it seems like caused by not being using the golang version not supported ( see https://book.kubebuilder.io/quick-start.html#prerequisites ) or an old bin where the fix was not done.

However, please feel free to re-open this one if you see that it is required.

**Closed by camilamacedo86** 2022-05-22 10:50 UTC
Labels: kind/bug

**Comment by islishude** [comment] 2023-03-26 02:49
I can replicate this issue, and I just got the reason.

because I have a `project` directory in my HOME path.

```console
$ ls 
go.mod  main.go
$ mkdir project
$ cat main.go
package main

import (
        "fmt"
        "os"
)

func main() {
        stat, err := os.Stat("PROJECT")
        if err != nil {
                panic(err)
        }
        fmt.Println(stat.Name(), stat.IsDir())
}
$ go run main.go
PROJECT true
```

I'm not sure why the os.Stat function is not case-sensitive, maybe it's a bug?

**Comment by xiao-jay** [comment] 2023-03-26 03:08
I think filesystem is not case-sensitive.
```
➜  test ls 
➜  test echo "aaa" > PROJECT
➜  test cat PROJECT 
aaa
➜  test mkdir project
mkdir: project: File exists
```
