### ISSUE TITLE
`kubebuilder version` returns unknown value

### ISSUE THREAD

**Issue by Joldnine** [kubernetes-sigs/kubebuilder#1576] opened 2020-06-27 12:13 UTC
`$ kubebuilder version` returns 
`Version: version.Version{KubeBuilderVersion:"unknown", KubernetesVendor:"unknown", GitCommit:"$Format:%H$", BuildDate:"1970-01-01T00:00:00Z", GoOs:"unknown", GoArch:"unknown"}`

* go version
go version go1.14.4 darwin/amd64
* Kubernetes & kubectl versions (just run `kubectl version` against your API server)
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

/kind bug

**Comment by camilamacedo86** [comment] 2020-06-30 01:15
I am unable to reproduce;

```
 kubebuilder version
Version: version.Version{KubeBuilderVersion:"2.3.1", KubernetesVendor:"1.16.4", GitCommit:"8b53abeb4280186e494b726edf8f54ca7aa64a49", BuildDate:"2020-03-26T16:42:00Z", GoOs:"unknown", GoArch:"unknown"}
```

Could you please try to check with go 1.13? the project does not support 1.14 yet.

**Comment by Joldnine** [comment] 2020-07-01 11:42
Hi, after switching go version to 1.13.12. The issue persists..
```
$ go version
go version go1.13.12 darwin/amd64
```

**Comment by camilamacedo86** [comment] 2020-07-01 15:22
Hi @Joldnine, 

How did you install the tool? Are you using a binary or master? Also, if. is via the master could you please let us know if it is inside of the GOPATH and with the path $GOPATH/sigs.k8s.io/kubebuilder?

**Comment by tengqm** [comment] 2020-07-03 09:30
Looks to me this has something to do with the facilities ([goreleaser](https://goreleaser.com/quick-start/)) used for generating release artifacts.
If you check the code, the `KubeBuilderVersion` is defaulted to "unknown" and never assigned a value in the code base.
The binary gets a version value through the `-X sigs.k8s.io/kubebuilder/cmd/version.kubeBuilderVersion=2.3.1` kind of `go build` flags. This means:

- if you are doing `make build`, you will get an "unknown" version;
- if you are doing `./test.sh` without specifying `INJECT_KB_VERSION`, you will get an "unknown" version too.

**Comment by camilamacedo86** [comment] 2020-07-11 18:00
Hi @Joldnine, 

Is the information provided so far enough? Can we close this one? 
If not, please let us know how did you install kubebuilder.

**Comment by estroz** [comment] 2020-07-14 23:42
Yes I believe this is intended behavior

/close

**Closed** 2020-07-14 23:42 UTC
Labels: kind/bug
