### ISSUE TITLE
Alternative Scaffolding Paths

### ISSUE THREAD

**Issue by shaneutt** [kubernetes-sigs/kubebuilder#2393] opened 2021-10-21 16:36 UTC
### What do you want to happen?

It was suggested of me to open this issue based on a conversation in the community call 2021-10-21.

Historically for multiple projects I've dealt with the hardcoded paths around scaffolding by generating stuff and then moving the files around and manually patching them for different paths, e.t.c.

The purpose of this request is to have a standard programmatic way to target alternative directories for scaffolding (e.g. in my own use case I have multiple projects that put `controllers` under `internal/controllers` for instance, and `apis/` under `pkg/apis`) which is documented.

I'm aware of the phase 2 plugins project:

- https://github.com/kubernetes-sigs/kubebuilder/issues/1378
- https://github.com/kubernetes-sigs/kubebuilder/pull/2338

This project may provide enough tooling to better support alternative paths, if in addition to this project we also added a documentation guide which shows a working example of solving this problem with a plugin, I would consider that sufficient to consider this issue resolved.

**Comment by estroz** [comment] 2021-11-04 16:20
Duplicate of #932

/triage duplicate
/close

**Closed** 2021-11-04 16:20 UTC
Labels: triage/duplicate, kind/feature
